In [1]:
import csv
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("x-ken-all.csv", encoding = "shift-jis")
df.columns = ['id', 'id2', 'post_id', 'prefecture_kana', 'municipalitie_kana', 'another_name_kana', 'prefecture', 'municipalitie', 'another_name', 'a', 'b', "c", 'd', 'e', 'f']
df["post_id"] = df["post_id"].astype(str).str.zfill(7)
df

,id,id2,post_id,prefecture_kana,municipalitie_kana,another_name_kana,prefecture,municipalitie,another_name,a,b,c,d,e,f
0,1101,64,0640941,ﾎｯｶｲﾄﾞｳ,ｻｯﾎﾟﾛｼﾁｭｳｵｳｸ,ｱｻﾋｶﾞｵｶ,北海道,札幌市中央区,旭ケ丘,0,0,1,0,0,0
1,1101,60,0600041,ﾎｯｶｲﾄﾞｳ,ｻｯﾎﾟﾛｼﾁｭｳｵｳｸ,ｵｵﾄﾞｵﾘﾋｶﾞｼ,北海道,札幌市中央区,大通東,0,0,1,0,0,0
2,1101,60,0600042,ﾎｯｶｲﾄﾞｳ,ｻｯﾎﾟﾛｼﾁｭｳｵｳｸ,ｵｵﾄﾞｵﾘﾆｼ,北海道,札幌市中央区,大通西,1,0,1,0,0,0
3,1101,64,0640820,ﾎｯｶｲﾄﾞｳ,ｻｯﾎﾟﾛｼﾁｭｳｵｳｸ,ｵｵﾄﾞｵﾘﾆｼ,北海道,札幌市中央区,大通西,1,0,1,0,0,0
4,1101,60,0600031,ﾎｯｶｲﾄﾞｳ,ｻｯﾎﾟﾛｼﾁｭｳｵｳｸ,ｷﾀ1ｼﾞｮｳﾋｶﾞｼ,北海道,札幌市中央区,北一条東,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127393,47381,90714,9071433,ｵｷﾅﾜｹﾝ,ﾔｴﾔﾏｸﾞﾝﾀｹﾄﾐﾁｮｳ,ﾊｲﾐﾅｶ,沖縄県,八重山郡竹富町,南風見仲,0,0,0,0,0,0
127394,47381,90717,9071751,ｵｷﾅﾜｹﾝ,ﾔｴﾔﾏｸﾞﾝﾀｹﾄﾐﾁｮｳ,ﾊﾃﾙﾏ,沖縄県,八重山郡竹富町,波照間,0,0,0,0,0,0
127395,47381,90715,9071544,ｵｷﾅﾜｹﾝ,ﾔｴﾔﾏｸﾞﾝﾀｹﾄﾐﾁｮｳ,ﾊﾄﾏ,沖縄県,八重山郡竹富町,鳩間,0,0,0,0,0,0
127396,47382,90718,9071800,ｵｷﾅﾜｹﾝ,ﾔｴﾔﾏｸﾞﾝﾖﾅｸﾞﾆﾁｮｳ,NaN,沖縄県,八重山郡与那国町,NaN,0,0,0,0,0,0
127397,47382,90718,9071801,ｵｷﾅﾜｹﾝ,ﾔｴﾔﾏｸﾞﾝﾖﾅｸﾞﾆﾁｮｳ,ﾖﾅｸﾞﾆ,沖縄県,八重山郡与那国町,与那国,0,0,0,0,0,0

In [3]:
df[['post_id', 'prefecture', 'municipalitie', 'another_name']]

        post_id prefecture municipalitie another_name
0       0640941        北海道        札幌市中央区          旭ケ丘
1       0600041        北海道        札幌市中央区          大通東
2       0600042        北海道        札幌市中央区          大通西
3       0640820        北海道        札幌市中央区          大通西
4       0600031        北海道        札幌市中央区         北一条東
...         ...        ...           ...          ...
127393  9071433        沖縄県       八重山郡竹富町         南風見仲
127394  9071751        沖縄県       八重山郡竹富町          波照間
127395  9071544        沖縄県       八重山郡竹富町           鳩間
127396  9071800        沖縄県      八重山郡与那国町          NaN
127397  9071801        沖縄県      八重山郡与那国町          与那国

[127398 rows x 4 columns]

In [4]:
prefectures = df["prefecture"] .unique()
prefectures

array(['北海道', '青森県', '岩手県', '宮城県', '秋田県', '山形県', '福島県', '茨城県', '栃木県',
       '群馬県', '埼玉県', '千葉県', '東京都', '神奈川県', '新潟県', '富山県', '石川県', '福井県',
       '山梨県', '長野県', '岐阜県', '静岡県', '愛知県', '三重県', '滋賀県', '京都府', '大阪府',
       '兵庫県', '奈良県', '和歌山県', '鳥取県', '島根県', '岡山県', '広島県', '山口県', '徳島県',
       '香川県', '愛媛県', '高知県', '福岡県', '佐賀県', '長崎県', '熊本県', '大分県', '宮崎県',
       '鹿児島県', '沖縄県'], dtype=object)

In [5]:
df_prefecture_names = pd.DataFrame(prefectures, columns=["prefecture"])
df_prefecture_names_kana = pd.DataFrame(df["prefecture_kana"] .unique(), columns=["prefecture_kana"])
def_serial_prefecture_id = pd.DataFrame(pd.RangeIndex(start=1, stop=len(df_prefecture_names.index) + 1, step=1), columns=["prefecture_id"])

df_prefectures = pd.concat([def_serial_prefecture_id, df_prefecture_names, df_prefecture_names_kana], axis=1, join='outer')
df_prefectures.to_csv("csv/prefectures.csv",index=None)
df_prefectures

    prefecture_id prefecture prefecture_kana
0               1        北海道         ﾎｯｶｲﾄﾞｳ
1               2        青森県          ｱｵﾓﾘｹﾝ
2               3        岩手県           ｲﾜﾃｹﾝ
3               4        宮城県          ﾐﾔｷﾞｹﾝ
4               5        秋田県           ｱｷﾀｹﾝ
5               6        山形県         ﾔﾏｶﾞﾀｹﾝ
6               7        福島県          ﾌｸｼﾏｹﾝ
7               8        茨城県         ｲﾊﾞﾗｷｹﾝ
8               9        栃木県          ﾄﾁｷﾞｹﾝ
9              10        群馬県          ｸﾞﾝﾏｹﾝ
10             11        埼玉県          ｻｲﾀﾏｹﾝ
11             12        千葉県           ﾁﾊﾞｹﾝ
12             13        東京都          ﾄｳｷｮｳﾄ
13             14       神奈川県         ｶﾅｶﾞﾜｹﾝ
14             15        新潟県         ﾆｲｶﾞﾀｹﾝ
15             16        富山県           ﾄﾔﾏｹﾝ
16             17        石川県          ｲｼｶﾜｹﾝ
17             18        福井県           ﾌｸｲｹﾝ
18             19        山梨県          ﾔﾏﾅｼｹﾝ
19             20        長野県          ﾅｶﾞﾉｹﾝ
20             21        岐阜県           ｷﾞﾌｹﾝ
21             22        静岡県         ｼｽﾞｵｶｹﾝ
22             23        愛知県           ｱｲﾁｹﾝ
23             24        三重県            ﾐｴｹﾝ
24             25        滋賀県           ｼｶﾞｹﾝ
25             26        京都府           ｷｮｳﾄﾌ
26             27        大阪府           ｵｵｻｶﾌ
27             28        兵庫県         ﾋｮｳｺﾞｹﾝ
28             29        奈良県            ﾅﾗｹﾝ
29             30       和歌山県          ﾜｶﾔﾏｹﾝ
30             31        鳥取県          ﾄｯﾄﾘｹﾝ
31             32        島根県           ｼﾏﾈｹﾝ
32             33        岡山県          ｵｶﾔﾏｹﾝ
33             34        広島県          ﾋﾛｼﾏｹﾝ
34             35        山口県         ﾔﾏｸﾞﾁｹﾝ
35             36        徳島県          ﾄｸｼﾏｹﾝ
36             37        香川県          ｶｶﾞﾜｹﾝ
37             38        愛媛県           ｴﾋﾒｹﾝ
38             39        高知県           ｺｳﾁｹﾝ
39             40        福岡県          ﾌｸｵｶｹﾝ
40             41        佐賀県           ｻｶﾞｹﾝ
41             42        長崎県         ﾅｶﾞｻｷｹﾝ
42             43        熊本県          ｸﾏﾓﾄｹﾝ
43             44        大分県          ｵｵｲﾀｹﾝ
44             45        宮崎県         ﾐﾔｻﾞｷｹﾝ
45             46       鹿児島県         ｶｺﾞｼﾏｹﾝ
46             47        沖縄県          ｵｷﾅﾜｹﾝ

In [6]:
from pykakasi import kakasi
kakasi = kakasi()
kakasi.setMode('H', 'a')
kakasi.setMode('K', 'a')
kakasi.setMode('J', 'a')
conv = kakasi.getConverter()

In [43]:
def create_municipalitie_csv(name):
    df_prefecture_data = df[df["prefecture"] == name]

    df_municipalitie_names = pd.DataFrame(df_prefecture_data["municipalitie"].unique(),columns=["municipalitie"])
    df_municipalitie_names_kana = pd.DataFrame(df_prefecture_data["municipalitie_kana"].unique(),columns=["municipalitie_kana"])
    
    def_serial_municipalitie_id = pd.DataFrame(pd.RangeIndex(start=1, stop=len(df_municipalitie_names.index) + 1, step=1), columns=["municipalitie_id"])
    
    df_municipalities = pd.concat([def_serial_municipalitie_id, df_municipalitie_names, df_municipalitie_names_kana], axis=1, join='outer')
    prefecture_id = df_prefectures[df_prefectures["prefecture"] == name]["prefecture_id"].values[0]
    df_municipalities["prefecture_id"] = df_prefectures[df_prefectures["prefecture"] == name]["prefecture_id"].values[0]

    df_municipalities.to_csv("csv/municipalities/" + conv.do(name) + ".csv", index=None)
    
    return df_municipalities, prefecture_id
    
def create_another_name_csv(name, municipalitie_name, df_municipalities, prefecture_id):
        
        s_another_name = df["another_name"].unique()
        s_another_name_kana = df["another_name_kana"].unique()
        
        post_nums =  []
        for s in s_another_name:
            if ((df["another_name"] == s) & (df["municipalitie"] == municipalitie_name) & (df["prefecture"] == name)).empty:
                
                post_num = df[((df["another_name"] == s) & (df["municipalitie"] == municipalitie_name) & df["prefecture"] == name)]["post_id"]
                post_nums.append(post_num.values)
                print (post_num)
        print(post_nums)
                
        post_numpy_list = np.array(post_nums)

        df_another_name = pd.DataFrame(s_another_name)
        df_another_name_kana = pd.DataFrame(s_another_name_kana)
        
        df_post_num = pd.DataFrame(post_numpy_list)
        
        df_another_names = pd.concat([df_another_name, df_another_name_kana,df_post_num], axis=1, join='outer')

        df_another_names.to_csv("csv/another_names/" + conv.do(municipalitie_name) + ".csv", index=None, header=["another_name","another_name_kana", "post_id"])

import glob
import re
import os

for name in prefectures:
    df_municipalitie_data, prefecture_id = create_municipalitie_csv(name)
       
    municipalities = df_municipalitie_data["municipalitie"].unique()
    for municipalitie_name in municipalities:
        df_municipalitie = df[df["municipalitie"] == municipalitie_name]

        s_another_name = df_municipalitie["another_name"].unique()
        s_another_name_kana = df_municipalitie["another_name_kana"].unique()

        post_nums =  []
        for s in s_another_name:
            values = df[((df["another_name"] == s) & (df["municipalitie"] == municipalitie_name))]["post_id"].values
            if values.size == 1:
                post_nums.append(values[0])
            else:
                 post_nums.append("0")

        post_numpy_list = np.array(post_nums)

        df_another_name = pd.DataFrame(s_another_name, columns=["another_name"])
        df_another_name_kana = pd.DataFrame(s_another_name_kana, columns=["another_name_kana"])

        df_post_num = pd.DataFrame(post_numpy_list, columns=["post_id"])
        df_post_num["post_id"] = df_post_num["post_id"].astype('str').str.zfill(7)
        print(df_post_num["post_id"])
        df_another_names = pd.concat([df_another_name, df_another_name_kana,df_post_num], axis=1, join='outer')
        df_another_names["prefecture_id"] = prefecture_id

        df_another_names.to_csv("csv/another_names/" + conv.do(municipalitie_name) + ".csv", index=None)
    
#     prefecture_id = df_prefectures[df_prefectures["prefecture"] == name]["prefecture_id"].values[0]
#     municipalities = df_municipalities["municipalitie"].unique()
    
#     for municipalitie_name in municipalities:
#         create_another_name_csv(name, municipalitie_name, df_municipalities, prefecture_id)

0     0640941
1     0600041
2     0000000
3     0600031
4     0000000
       ...
73    0640958
74    0640951
75    0640952
76    0640953
77    0640954
Name: post_id, Length: 78, dtype: object
0      0000000
1      0028071
2      0028072
3      0028073
4      0028074
        ...
127    0028044
128    0028045
129    0028091
130    0028081
131    0028082
Name: post_id, Length: 132, dtype: object
0      0000000
1      0070880
2      0070881
3      0070882
4      0070883
        ...
112    0070873
113    0070874
114    0650041
115    0650042
116    0070011
Name: post_id, Length: 117, dtype: object
0     0000000
1     0030851
2     0030852
3     0030853
4     0030854
       ...
71    0030872
72    0030873
73    0030874
74    0030875
75    0030030
Name: post_id, Length: 76, dtype: object
0     0000000
1     0620911
2     0620912
3     0620020
4     0620021
5     0620022
6     0620023
7     0620024
8     0620025
9     0620051
10    0620052
11    0620053
12    0620054
13    0620055
14    0620901
15    0620902
16    0620903
17    0620904
18    0620905
19    0620906
20    0620907
21    0620908
22    0620909
23    0620921
24    0620922
25    0620039
26    0620031
27    0620032
28    0620033
29    0620034
30    0620035
31    0620045
32    0620931
33    0620932
34    0620933
35    0620934
36    0620935
37    0620936
38    0620937
39    0620938
40    0620041
41    0620042
42    0620043
43    0620001
44    0620002
45    0620003
46    0620004
47    0620005
48    0620006
49    0620007
50    0620008
51    0620009
52    0620010
53    0620011
54    0620012
Name: post_id, dtype: object
0     0000000
1     0050849
2     0050850
3     0050841
4     0050842
       ...
90    0050037
91    0050038
92    0050039
93    0050040
94    0050041
Name: post_id, Length: 95, dtype: object
0     0000000
1     0630811
2     0630812
3     0630813
4     0630814
       ...
77    0630003
78    0630004
79    0630005
80    0630006
81    0630007
Name: post_id, Length: 82, dtype: object
0     0000000
1     0040021
2     0040071
3     0040072
4     0040073
5     0040074
6     0040075
7     0040076
8     0040051
9     0040052
10    0040053
11    0040054
12    0040055
13    0040039
14    0040007
15    0040006
16    0040069
17    0040068
18    0040061
19    0040062
20    0040063
21    0040064
22    0040065
23    0040001
24    0040002
25    0040003
26    0040004
27    0040005
28    0040022
29    0040041
30    0040042
31    0040031
32    0040032
33    0040033
34    0040015
35    0040011
36    0040013
37    0040012
38    0040014
Name: post_id, dtype: object
0     0000000
1     0060831
2     0060832
3     0060833
4     0060834
       ...
67    0060819
68    0060820
69    0060821
70    0060822
71    0060823
Name: post_id, Length: 72, dtype: object
0     0000000
1     0040821
2     0040811
3     0040812
4     0040813
5     0040814
6     0040815
7     0040861
8     0040862
9     0040863
10    0040864
11    0040865
12    0040866
13    0040867
14    0040859
15    0040841
16    0040842
17    0040843
18    0040844
19    0040845
20    0040846
21    0040847
22    0040848
23    0040849
24    0040840
25    0040809
26    0040801
27    0040802
28    0040803
29    0040804
30    0040805
31    0040839
32    0040831
33    0040832
34    0040833
35    0040834
36    0040835
37    0040836
38    0040889
39    0040871
40    0040872
41    0040873
42    0040874
43    0040875
44    0040876
45    0040877
46    0040878
47    0040879
48    0040880
49    0040881
50    0040882
Name: post_id, dtype: object
0      0000000
1      0400044
2      0410805
3      0410804
4      0420913
        ...
163    0400056
164    0420932
165    0420933
166    0400077
167    0400063
Name: post_id, Length: 168, dtype: object
0     0000000
1     0470028
2     0470046
3     0470035
4     0470151
5     0470154
6     0470006
7     0470038
8     0470032
9     0470021
10    0470031
11    0470044
12    0470013
13    0482561
14    0482671
15    0470005
16    0470264
17    0470037
18    0470027
19    0470156
20    0470002
21    0482672
22    0470026
23    0470045
24    0470047
25    0470152
26    0470153
27    0470004
28    0470042
29    0470014
30    0470015
31    0000000
32    0470048
33    0470008
34    0470041
35    0470012
36    0470011
37    0470033
38    0470043
39    0470036
40    0470039
41    0470016
42    0470024
43    0470266
44    0470265
45    0470157
46    0470155
47    0470262
48    0470003
49    0470022
50    0470034
51    0470007
52    0470263
53    0470023
54    0482673
55    0470025
56    0482562
57    0470001
58    0470017
Name: post_id, dtype: object
0      0000000
1      0798401
2      0798402
3      0798403
4      0700072
        ...
328    0700058
329    0000000
330    0700059
331    0000000
332    0788221
Name: post_id, Length: 333, dtype: object
0     0000000
1     0500051
2     0510023
3     0510035
4     0500086
5     0510033
6     0510022
7     0500052
8     0500064
9     0500053
10    0510032
11    0500063
12    0510002
13    0500082
14    0510016
15    0510014
16    0500055
17    0510027
18    0510026
19    0510036
20    0510005
21    0500067
22    0500072
23    0500062
24    0510006
25    0510011
26    0500076
27    0510031
28    0500077
29    0510025
30    0500074
31    0500075
32    0500087
33    0510028
34    0500054
35    0500061
36    0500083
37    0500081
38    0510013
39    0510003
40    0510004
41    0500066
42    0510015
43    0510024
44    0510034
45    0510001
46    0500071
47    0510021
48    0500073
49    0500084
50    0500065
51    0510012
52    0500085
Name: post_id, dtype: object
0      0000000
1      0850062
2      0850058
3      0850057
4      0850252
        ...
175    0850834
176    0850842
177    0850042
178    0850036
179    0850033
Name: post_id, Length: 180, dtype: object
0      0000000
1      0891181
2      0891245
3      0891244
4      0800835
        ...
135    0800857
136    0800856
137    0802331
138    0802336
139    0800817
Name: post_id, Length: 140, dtype: object
0      0000000
1      0990871
2      0900018
3      0900011
4      0900803
        ...
159    0910008
160    0910001
161    0910155
162    0900057
163    0900808
Name: post_id, Length: 164, dtype: object
0     0000000
1     0680405
2     0680754
3     0680662
4     0680673
5     0680661
6     0680665
7     0680663
8     0680664
9     0680672
10    0680675
11    0680671
12    0680674
13    0680413
14    0680412
15    0680414
16    0680531
17    0680532
18    0680533
19    0680535
20    0680534
21    0680402
22    0680404
23    0680411
24    0680406
25    0680401
26    0680756
27    0680424
28    0680409
29    0680421
30    0680408
31    0680426
32    0680546
33    0680545
34    0680541
35    0680544
36    0680546
37    0680548
38    0680547
39    0680540
40    0680549
41    0680542
42    0680543
43    0680751
44    0680753
45    0680422
46    0680407
47    0680423
48    0680403
49    0680752
50    0680536
51    0680755
52    0680425
Name: post_id, dtype: object
0      0000000
1      0683185
2      0680035
3      0680034
4      0790183
        ...
177    0680011
178    0680031
179    0680012
180    0680032
181    0680033
Name: post_id, Length: 182, dtype: object
0     0000000
1     0993115
2     0930135
3     0993502
4     0930045
       ...
87    0930085
88    0993111
89    0992422
90    0993116
91    0992421
Name: post_id, Length: 92, dtype: object
0     0000000
1     0770041
2     0770043
3     0770023
4     0770026
5     0770048
6     0770012
7     0770037
8     0770042
9     0770003
10    0770038
11    0770031
12    0770007
13    0770001
14    0770002
15    0770011
16    0770006
17    0770027
18    0770047
19    0770021
20    0783167
21    0770024
22    0770013
23    0783166
24    0770044
25    0770025
26    0770028
27    0770036
28    0783162
29    0783165
30    0770005
31    0770034
32    0770022
33    0783168
34    0770045
35    0770015
36    0770046
37    0783163
38    0770014
39    0770033
40    0770032
41    0770016
42    0770004
43    0000000
44    0783161
45    0783164
46    0000000
47    0770035
Name: post_id, dtype: object
0     0000000
1     0530807
2     0530054
3     0530051
4     0000000
       ...
93    0530053
94    0530851
95    0530802
96    0591372
97    0530021
Name: post_id, Length: 98, dtype: object

0     0000000
1     0970015
2     0970025
3     0970023
4     0986642
5     0000000
6     0986565
7     0986572
8     0986561
9     0986562
10    0986574
11    0986564
12    0986576
13    0986645
14    0986642
15    0984582
16    0986573
17    0986575
18    0986563
19    0986571
20    0986643
21    0970003
22    0970017
23    0970002
24    0970014
25    0970007
26    0970006
27    0970001
28    0986758
29    0000000
30    0986754
31    0986755
32    0986756
33    0986751
34    0986385
35    0986644
36    0986757
37    0986384
38    0970005
39    0970022
40    0970012
41    0970037
42    0970026
43    0970016
44    0000000
45    0984581
46    0984581
47    0984581
48    0984581
49    0970036
50    0970011
51    0970027
52    0970024
53    0970004
54    0970021
55    0970013
Name: post_id, dtype: object
0      0000000
1      0720044
2      0720023
3      0720021
4      0720011
        ...
111    0720814
112    0790173
113    0790172
114    0790174
115    0790175
Name: post_id, Length: 116, dtype: object
0     0000000
1     0750165
2     0750036
3     0750035
4     0760081
5     0791371
6     0750166
7     0750011
8     0750001
9     0750012
10    0750002
11    0750013
12    0750003
13    0750014
14    0750004
15    0750015
16    0750005
17    0750016
18    0750006
19    0750007
20    0750252
21    0750251
22    0750019
23    0750018
24    0750254
25    0750253
26    0750167
27    0750161
28    0791372
29    0750162
30    0750017
31    0750034
32    0750041
33    0750031
34    0750021
35    0750032
36    0750033
37    0750164
38    0750163
Name: post_id, dtype: object
0     0000000
1     0670011
2     0670012
3     0670013
4     0670014
       ...
86    0670054
87    0670073
88    0670065
89    0670066
90    0670004
Name: post_id, Length: 91, dtype: object
0     0000000
1     0791143
2     0791134
3     0791274
4     0791141
5     0791121
6     0791101
7     0791154
8     0791152
9     0791155
10    0791156
11    0791124
12    0791133
13    0791135
14    0791131
15    0791122
16    0791142
17    0791132
18    0791123
19    0791272
20    0791273
21    0791271
22    0791287
23    0791281
24    0791282
25    0791283
26    0791286
27    0791284
28    0791285
29    0791153
30    0791102
31    0791136
32    0791144
33    0791151
34    0791266
35    0791264
36    0791262
37    0791266
38    0791262
39    0791265
40    0791261
41    0791261
42    0791263
43    0791264
44    0791267
45    0791268
46    0791113
47    0791112
48    0791114
49    0791111
Name: post_id, dtype: object
0     0000000
1     0996131
2     0940021
3     0940007
4     0940031
5     0940027
6     0995354
7     0995364
8     0995362
9     0995355
10    0995351
11    0995363
12    0995353
13    0995352
14    0995365
15    0995361
16    0940025
17    0940001
18    0996133
19    0940026
20    0996132
21    0940005
22    0940006
23    0996242
24    0995171
25    0995174
26    0995175
27    0995172
28    0995173
29    0940012
30    0940022
31    0996241
32    0940015
33    0940003
34    0940004
35    0940002
36    0940014
37    0940011
38    0940013
39    0940023
40    0940024
41    0996131
Name: post_id, dtype: object
0     0000000
1     0950403
2     0950405
3     0950401
4     0950402
5     0950406
6     0950404
7     0950019
8     0950029
9     0950039
10    0950181
11    0950182
12    0950183
13    0950052
14    0950371
15    0950064
16    0950051
17    0950061
18    0950053
19    0980475
20    0950043
21    0950063
22    0950056
23    0950021
24    0950022
25    0950023
26    0950024
27    0950025
28    0950031
29    0950032
30    0950033
31    0950034
32    0950035
33    0950045
34    0950044
35    0950011
36    0950012
37    0950013
38    0950014
39    0950015
40    0950016
41    0950017
42    0950018
43    0950041
44    0950042
45    0950048
46    0950001
47    0950002
48    0950003
49    0950004
50    0950005
51    0950006
52    0950007
53    0950008
54    0950054
55    0950062
56    0950055
57    0950046
58    0950047
Name: post_id, dtype: object
0     0000000
1     0960075
2     0960061
3     0960010
4     0960030
       ...
73    0980504
74    0960072
75    0960077
76    0960063
77    0960074
Name: post_id, Length: 78, dtype: object
0     0000000
1     0682151
2     0682112
3     0682114
4     0682118
5     0682115
6     0682117
7     0682111
8     0682113
9     0682116
10    0682164
11    0682167
12    0682165
13    0682108
14    0682101
15    0682166
16    0682162
17    0682105
18    0682153
19    0682155
20    0682154
21    0682152
22    0682163
23    0682158
24    0682137
25    0682136
26    0682131
27    0682134
28    0682133
29    0682132
30    0682135
31    0682102
32    0682104
33    0682146
34    0682144
35    0682147
36    0682142
37    0682148
38    0682143
39    0682145
40    0682161
41    0682141
42    0682103
43    0682106
44    0682156
45    0682168
46    0682121
47    0682125
48    0682122
49    0682124
50    0682128
51    0682123
52    0682127
53    0682126
54    0682107
55    0682157
Name: post_id, dtype: object
0     0000000
1     0860061
2     0870006
3     0870014
4     0860064
       ...
66    0870003
67    0870009
68    0870049
69    0860071
70    0860073
Name: post_id, Length: 71, dtype: object
0     0000000
1     0660015
2     0660014
3     0660018
4     0660043
       ...
77    0660024
78    0660078
79    0660068
80    0660019
81    0660057
Name: post_id, Length: 82, dtype: object
0     0000000
1     0730015
2     0730018
3     0730045
4     0730042
5     0730016
6     0730017
7     0790461
8     0790463
9     0790462
10    0730046
11    0730022
12    0730036
13    0730001
14    0730012
15    0730011
16    0730043
17    0730031
18    0730033
19    0730034
20    0730004
21    0730003
22    0730002
23    0730035
24    0730041
25    0730044
26    0730005
27    0730006
28    0730026
29    0730027
30    0730024
31    0730014
32    0730021
33    0730023
34    0730013
35    0730032
36    0730025
Name: post_id, dtype: object
0     0000000
1     0730107
2     0730116
3     0730118
4     0000000
       ...
60    0730158
61    0730122
62    0730159
63    0730123
64    0730124
Name: post_id, Length: 65, dtype: object
0    0000000
1    0730404
2    0730401
3    0730405
4    0730402
5    0730406
6    0730403
7    0730407
Name: post_id, dtype: object
0     0000000
1     0740001
2     0740002
3     0740003
4     0740004
5     0740005
6     0740006
7     0740007
8     0740008
9     0740009
10    0740031
11    0740028
12    0740021
13    0740143
14    0740142
15    0780151
16    0780153
17    0780154
18    0000000
19    0741276
20    0780152
21    0741273
22    0741162
23    0741161
24    0741275
25    0741274
26    0741271
27    0741163
28    0740014
29    0740024
30    0740023
31    0740144
32    0740141
33    0740147
34    0740025
35    0740027
36    0740026
37    0740012
38    0741271
39    0740016
40    0740015
41    0740013
42    0740022
43    0740145
44    0740011
45    0740146
Name: post_id, dtype: object
0      0000000
1      0760026
2      0760008
3      0760035
4      0760054
        ...
104    0760018
105    0760203
106    0760161
107    0760022
108    0760032
Name: post_id, Length: 109, dtype: object
0     0000000
1     0590027
2     0590017
3     0590016
4     0590552
5     0590031
6     0590553
7     0590022
8     0590021
9     0590002
10    0590033
11    0590023
12    0000000
13    0590001
14    0590015
15    0590032
16    0590003
17    0590012
18    0590011
19    0590462
20    0590028
21    0590463
22    0590551
23    0590464
24    0590465
25    0590466
26    0590014
27    0590013
28    0590036
29    0590024
30    0590025
31    0590004
32    0590035
33    0590026
34    0590034
Name: post_id, dtype: object
0     0000000
1     0611448
2     0611431
3     0611401
4     0611414
5     0611415
6     0611411
7     0611424
8     0611423
9     0611402
10    0611404
11    0611433
12    0611366
13    0611444
14    0611432
15    0611449
16    0611407
17    0611409
18    0611417
19    0611426
20    0611443
21    0611416
22    0611363
23    0611354
24    0611355
25    0611352
26    0611351
27    0611353
28    0611363
29    0611364
30    0611412
31    0611445
32    0611446
33    0611441
34    0611403
35    0611405
36    0611362
37    0611435
38    0611356
39    0611434
40    0611361
41    0611422
42    0611447
43    0611425
44    0611365
45    0611421
46    0611427
47    0611442
48    0611375
49    0611371
50    0611373
51    0611372
52    0611374
53    0611376
54    0611413
55    0611406
Name: post_id, dtype: object

0      0000000
1      0520015
2      0520025
3      0520002
4      0590151
        ...
300    9600808
301    9600805
302    9600806
303    9600802
304    9600486
Name: post_id, Length: 305, dtype: object
0     0000000
1     0611141
2     0611123
3     0611145
4     0611125
5     0611124
6     0611270
7     0611274
8     0611278
9     0611272
10    0611271
11    0611279
12    0611273
13    0611277
14    0611276
15    0611275
16    0611111
17    0611261
18    0611112
19    0611113
20    0611134
21    0611133
22    0611147
23    0611265
24    0611144
25    0611126
26    0611127
27    0611146
28    0611121
29    0611135
30    0611153
31    0000000
32    0611103
33    0611102
34    0611105
35    0611106
36    0611104
37    0611267
38    0611114
39    0611151
40    0611122
41    0611132
42    0611136
43    0611115
44    0611131
45    0611266
46    0611143
47    0611154
48    0611148
49    0611137
50    0611264
51    0611281
52    0611268
53    0611269
54    0611142
Name: post_id, dtype: object
0     0000000
1     0613601
2     0613602
3     0613151
4     0613603
       ...
87    0613232
88    0613221
89    0613222
90    0613223
91    0613363
Name: post_id, Length: 92, dtype: object
0     0000000
1     0411242
2     0411223
3     0411241
4     0490161
5     0490101
6     0490152
7     0411213
8     0490136
9     0490157
10    0490121
11    0490143
12    0490151
13    0411221
14    0490142
15    0411211
16    0490154
17    0490153
18    0490132
19    0490141
20    0490162
21    0411222
22    0490282
23    0490171
24    0490131
25    0490155
26    0490156
27    0411243
28    0490111
29    0490158
30    0411215
31    0490122
32    0411214
33    0411225
34    0411212
35    0411251
36    0411201
37    0490135
38    0490283
39    0411224
40    0490134
41    0411231
42    0411226
43    0411244
44    0490281
45    0490285
46    0490133
47    0490286
48    0490284
Name: post_id, dtype: object
0     0000000
1     0610201
2     0610253
3     0610252
4     0610251
5     0610254
6     0610254
7     0610232
8     0610212
9     0610218
10    0610207
11    0000000
12    0610217
13    0610216
14    0613772
15    0610205
16    0610233
17    0613777
18    0610224
19    0610227
20    0613771
21    0610215
22    0613773
23    0610211
24    0610226
25    0610234
26    0610213
27    0610221
28    0000000
29    0028089
30    0613779
31    0613776
32    0613778
33    0610208
34    0610235
35    0610225
36    0610203
37    0610228
38    0610222
39    0610202
40    0610223
41    0610231
42    0610204
43    0610214
Name: post_id, dtype: object
0     0000000
1     0681112
2     0681102
3     0681104
4     0681125
5     0681116
6     0681123
7     0681152
8     0681131
9     0681134
10    0681136
11    0681142
12    0681146
13    0681138
14    0681121
15    0681124
16    0681144
17    0681143
18    0681111
19    0681126
20    0681132
21    0681137
22    0681153
23    0681141
24    0681145
25    0681103
26    0681151
27    0681127
28    0681135
29    0681113
30    0681133
31    0681122
32    0681115
33    0681114
34    0681105
35    0681101
Name: post_id, dtype: object
0     0000000
1     0491643
2     0491517
3     0491504
4     0491523
5     0491771
6     0491503
7     0491522
8     0491781
9     0491521
10    0491761
11    0491506
12    0491783
13    0491784
14    0491642
15    0491644
16    0491524
17    0491763
18    0491513
19    0491782
20    0491501
21    0491641
22    0491515
23    0491514
24    0491507
25    0491505
26    0491762
27    0491516
28    0491512
29    0491764
30    0491502
31    0491511
32    0491645
Name: post_id, dtype: object
0     0000000
1     0491325
2     0491312
3     0491323
4     0491312
5     0491322
6     0491301
7     0491331
8     0491332
9     0491312
10    0491454
11    0491321
12    0491452
13    0491311
14    0491324
15    0491302
16    0491312
17    0491312
18    0491456
19    0491321
20    0491331
21    0491321
22    0491451
23    0491453
24    0491453
25    0491312
26    0491455
Name: post_id, dtype: object
0    0000000
1    0491103
2    0491105
3    0491107
4    0491101
5    0491106
6    0491102
7    0491221
8    0491104
Name: post_id, dtype: object
0     0000000
1     0490405
2     0490454
3     0490401
4     0490453
5     0490412
6     0490402
7     0490403
8     0490404
9     0490431
10    0490408
11    0490411
12    0490451
13    0490452
14    0490455
15    0490441
16    0490406
17    0490407
18    0490422
19    0490421
Name: post_id, dtype: object
0     0000000
1     0411136
2     0411352
3     0411122
4     0411121
5     0411354
6     0411353
7     0411104
8     0411105
9     0411134
10    0411102
11    0411132
12    0411133
13    0411131
14    0411112
15    0411112
16    0411355
17    0411101
18    0411351
19    0411103
20    0411111
21    0411135
Name: post_id, dtype: object
0    0000000
1    0411401
2    0411405
3    0411402
4    0411404
5    0411403
Name: post_id, dtype: object
0     0000000
1     0492142
2     0492463
3     0492311
4     0492465
5     0492301
6     0492312
7     0492327
8     0492324
9     0492141
10    0492308
11    0492222
12    0492221
13    0492223
14    0492461
15    0492307
16    0492304
17    0492305
18    0492323
19    0492462
20    0492303
21    0492306
22    0492322
23    0492464
24    0492325
25    0492302
26    0492326
27    0492313
28    0492321
Name: post_id, dtype: object
0     0000000
1     0493113
2     0492561
3     0493125
4     0493115
5     0492564
6     0493104
7     0493126
8     0492562
9     0493127
10    0492566
11    0493121
12    0430332
13    0430402
14    0430416
15    0430405
16    0430331
17    0430335
18    0430401
19    0430418
20    0430403
21    0430404
22    0430333
23    0430334
24    0430417
25    0430419
26    0430415
27    0493341
28    0493117
29    0492563
30    0492675
31    0493105
32    0492565
33    0493112
34    0493111
35    0493123
36    0493121
37    0493103
38    0493128
39    0492672
40    0493122
41    0493124
42    0493102
43    0492673
44    0493106
45    0493107
46    0493114
47    0493118
48    0493116
49    0493101
50    0492671
51    0493342
52    0492674
Name: post_id, dtype: object
0     0000000
1     0493521
2     0493519
3     0493511
4     0493521
5     0493501
6     0493521
7     0493521
8     0493517
9     0493515
10    0493462
11    0493516
12    0000000
13    0493521
14    0493521
15    0493521
16    0493521
17    0493465
18    0493502
19    0493514
20    0493464
21    0493463
22    0493512
23    0493461
24    0493504
25    0493513
26    0493501
27    0493521
28    0493521
29    0493521
30    0493503
Name: post_id, dtype: object
0     0000000
1     0430013
2     0430031
3     0430042
4     0430012
5     0430041
6     0430046
7     0430016
8     0430026
9     0430014
10    0430024
11    0430057
12    0430064
13    0430045
14    0430011
15    0430032
16    0430053
17    0430056
18    0430065
19    0430023
20    0430051
21    0430066
22    0430025
23    0430033
24    0430015
25    0430034
26    0430062
27    0430044
28    0430036
29    0430035
30    0430022
31    0430043
32    0430055
33    0430017
34    0430054
35    0430061
36    0430063
37    0430052
38    0430021
Name: post_id, dtype: object
0     0000000
1     0490741
2     0490621
3     0490607
4     0490604
5     0490603
6     0490611
7     0490601
8     0490626
9     0490612
10    0490622
11    0490606
12    0490605
13    0490627
14    0490608
15    0490623
16    0490561
17    0490742
18    0490743
19    0490625
20    0490624
21    0490744
22    0490564
23    0490602
24    0490563
25    0490613
26    0490562
Name: post_id, dtype: object
0     0000000
1     0431232
2     0431111
3     0431233
4     0431102
5     0431238
6     0431237
7     0431104
8     0431116
9     0431234
10    0431231
11    0431101
12    0000000
13    0431361
14    0431364
15    0431367
16    0431113
17    0431362
18    0431103
19    0431351
20    0431235
21    0431366
22    0431118
23    0431363
24    0431368
25    0431114
26    0431115
27    0431112
28    0431365
29    0431117
Name: post_id, dtype: object
0     0000000
1     0430116
2     0430114
3     0430112
4     0430113
5     0430233
6     0430101
7     0430104
8     0430115
9     0430231
10    0430111
11    0430232
12    0430117
13    0430234
14    0430103
15    0430102
Name: post_id, dtype: object

0     0000000
1     0431521
2     0431402
3     0431405
4     0431401
5     0431403
6     0431522
7     0431523
8     0431404
9     0000000
10    0431525
11    0431525
12    0431524
Name: post_id, dtype: object
0     0000000
1     0494303
2     0494312
3     0494301
4     0494325
5     0494308
6     0494155
7     0494327
8     0494157
9     0494304
10    0494335
11    0494311
12    0494326
13    0494314
14    0494332
15    0494315
16    0494321
17    0494336
18    0494156
19    0494306
20    0494331
21    0494324
22    0494337
23    0494154
24    0494305
25    0494333
26    0494307
27    0494153
28    0494323
29    0494302
30    0494151
31    0494313
32    0494322
33    0494317
34    0494316
35    0494152
36    0494334
37    0494318
Name: post_id, dtype: object
0     0000000
1     0494513
2     0494431
3     0494515
4     0494501
5     0494516
6     0494753
7     0494751
8     0494518
9     0494512
10    0494755
11    0494514
12    0494434
13    0494433
14    0494432
15    0494754
16    0494517
17    0494511
18    0494752
19    0494824
20    0494827
21    0494821
22    0494823
23    0494825
24    0494826
25    0000000
26    0494801
27    0494802
28    0494803
29    0494804
30    0494805
31    0494811
32    0494812
33    0494813
34    0494814
35    0494815
36    0494828
37    0494822
38    0430501
39    0430515
40    0430503
41    0430511
42    0430502
43    0430421
44    0430512
45    0430514
46    0430505
47    0430504
48    0430513
Name: post_id, dtype: object
0     0000000
1     0480602
2     0480623
3     0480613
4     0480611
5     0480634
6     0480631
7     0480621
8     0480601
9     0480612
10    0480622
11    0480614
12    0480633
13    0480603
14    0480604
15    0480632
Name: post_id, dtype: object
0     0000000
1     0480351
2     0480412
3     0480415
4     0480404
5     0480405
6     0480401
7     0480413
8     0480406
9     0480403
10    0480402
11    0480414
12    0480411
Name: post_id, dtype: object
0     0000000
1     0480136
2     0480116
3     0480124
4     0480114
5     0480133
6     0480112
7     0480135
8     0480145
9     0480141
10    0480126
11    0480101
12    0480134
13    0480122
14    0480117
15    0480143
16    0480132
17    0480142
18    0480113
19    0480111
20    0480123
21    0480131
22    0480115
23    0480121
24    0480137
25    0480144
26    0480127
27    0480125
Name: post_id, dtype: object
0     0000000
1     0481251
2     0481265
3     0481305
4     0481316
5     0481314
6     0481262
7     0481313
8     0481254
9     0481315
10    0481323
11    0481321
12    0481302
13    0481325
14    0481252
15    0481264
16    0481253
17    0481303
18    0481326
19    0481324
20    0481307
21    0481307
22    0481327
23    0481316
24    0481322
25    0481312
26    0481263
27    0481304
28    0481312
29    0481341
30    0481261
31    0481321
32    0481311
33    0481306
34    0481301
Name: post_id, dtype: object
0     0000000
1     0481531
2     0481562
3     0481553
4     0481542
5     0481551
6     0481522
7     0481512
8     0481554
9     0481543
10    0481563
11    0481511
12    0481521
13    0481561
14    0481501
15    0481502
16    0481552
17    0481544
18    0481541
Name: post_id, dtype: object
0     0000000
1     0481602
2     0481622
3     0481624
4     0481623
5     0481603
6     0481614
7     0481604
8     0481621
9     0481613
10    0481611
11    0481631
12    0481615
13    0481601
14    0481612
15    0481605
Name: post_id, dtype: object
0     0000000
1     0481752
2     0481711
3     0481722
4     0481723
5     0481712
6     0481741
7     0481751
8     0481724
9     0481721
10    0481731
Name: post_id, dtype: object
0     0000000
1     0440215
2     0440201
3     0440201
4     0440454
5     0440451
6     0440223
7     0440201
8     0440453
9     0440201
10    0440222
11    0440214
12    0440201
13    0440451
14    0440224
15    0440461
16    0440462
17    0440213
18    0440452
19    0440461
20    0440225
21    0440221
22    0440211
23    0440463
24    0440201
25    0440453
26    0440201
27    0440212
Name: post_id, dtype: object
0     0000000
1     0440122
2     0440112
3     0440131
4     0440111
5     0440101
6     0440132
7     0440125
8     0440124
9     0440113
10    0440121
11    0440123
Name: post_id, dtype: object
0     0000000
1     0440083
2     0440064
3     0440082
4     0440078
5     0440071
6     0440001
7     0440051
8     0440002
9     0440052
10    0440003
11    0440053
12    0440004
13    0440054
14    0440005
15    0440055
16    0440006
17    0440056
18    0440007
19    0440057
20    0440066
21    0440063
22    0440076
23    0440065
24    0440074
25    0440085
26    0440073
27    0440084
28    0440077
29    0440075
30    0440062
31    0440067
32    0440068
33    0440011
34    0440031
35    0440012
36    0440032
37    0440013
38    0440033
39    0440014
40    0440034
41    0440015
42    0440035
43    0440016
44    0440036
45    0440021
46    0440041
47    0440022
48    0440042
49    0440023
50    0440043
51    0440024
52    0440044
53    0440025
54    0440045
55    0440072
56    0440081
57    0440061
Name: post_id, dtype: object
0     0000000
1     0450032
2     0482143
3     0482142
4     0450122
5     0450121
6     0482201
7     0482202
8     0450123
9     0450031
10    0482141
Name: post_id, dtype: object
0     0000000
1     0450023
2     0450001
3     0450022
4     0450011
5     0450025
6     0450013
7     0450024
8     0450002
9     0450003
10    0450026
11    0450012
12    0450021
Name: post_id, dtype: object
0    0000000
1    0450205
2    0450202
3    0450204
4    0450203
5    0450201
Name: post_id, dtype: object
0    0000000
1    0450302
2    0450301
3    0450303
Name: post_id, dtype: object
0     0000000
1     0460327
2     0460321
3     0460324
4     0460325
5     0460201
6     0460326
7     0460202
8     0460328
9     0460322
10    0460323
Name: post_id, dtype: object
0     0000000
1     0460104
2     0460132
3     0460133
4     0460111
5     0460131
6     0460112
7     0460121
8     0460103
9     0460102
10    0460101
11    0460113
Name: post_id, dtype: object
0     0000000
1     0482401
2     0000000
3     0482334
4     0482405
5     0482335
6     0482403
7     0482404
8     0482332
9     0482333
10    0482406
11    0482411
12    0482412
13    0482413
Name: post_id, dtype: object
0     0000000
1     0460015
2     0460011
3     0460023
4     0460004
5     0460003
6     0460001
7     0460022
8     0460033
9     0460031
10    0460025
11    0460013
12    0460032
13    0460002
14    0460021
15    0460014
16    0460024
17    0460012
Name: post_id, dtype: object
0     0000000
1     0460501
2     0460531
3     0460521
4     0460561
5     0460571
6     0460551
7     0460532
8     0460511
9     0460542
10    0460541
11    0460552
12    0460512
Name: post_id, dtype: object
0     0000000
1     0690239
2     0690231
3     0690237
4     0690235
5     0690236
6     0690233
7     0690234
8     0690232
9     0690207
10    0690208
11    0690209
12    0690210
13    0690211
14    0690212
15    0690213
16    0690214
17    0690215
18    0690216
19    0690217
20    0690218
21    0690219
22    0690220
23    0690221
24    0690238
Name: post_id, dtype: object
0     0000000
1     0790301
2     0790312
3     0790316
4     0790315
5     0790305
6     0790302
7     0790306
8     0790313
9     0790317
10    0790314
11    0790304
12    0790303
13    0790311
Name: post_id, dtype: object
0     0000000
1     0730205
2     0730212
3     0730221
4     0730222
5     0730201
6     0730203
7     0730211
8     0730202
9     0730206
10    0730204
11    0730213
Name: post_id, dtype: object
0     0000000
1     0691211
2     0691207
3     0691141
4     0000000
5     0691217
6     0691204
7     0691205
8     0691203
9     0691219
10    0691143
11    0000000
12    0691142
13    0691218
14    0691202
15    0691216
16    0691201
17    0691206
18    0691133
19    0691131
20    0691132
21    0691134
22    0000000
23    0691208
24    0691212
Name: post_id, dtype: object
0     0000000
1     0691335
2     0691344
3     0691343
4     0691321
       ...
85    0691314
86    0691315
87    0691316
88    0691329
89    0691485
Name: post_id, Length: 90, dtype: object
0     0000000
1     0691513
2     0691507
3     0680351
4     0691503
5     0680352
6     0691524
7     0691504
8     0691506
9     0691523
10    0691501
11    0000000
12    0680361
13    0691511
14    0680353
15    0691522
16    0691521
17    0691502
18    0680354
19    0691526
20    0691505
21    0691512
22    0680362
23    0680363
24    0691525
25    0680355
26    0691503
27    0680356
28    0680357
29    0691502
30    0691508
Name: post_id, dtype: object

0     0000000
1     0610518
2     0610514
3     0681231
4     0610517
5     0610502
6     0610527
7     0610508
8     0610515
9     0610505
10    0610512
11    0610511
12    0610523
13    0610525
14    0610506
15    0610501
16    0610526
17    0610504
18    0610516
19    0610528
20    0610529
21    0610522
22    0610503
23    0610513
24    0610521
25    0610507
26    0610524
Name: post_id, dtype: object
0     0000000
1     0610611
2     0610612
3     0610613
4     0610614
5     0610615
6     0610616
7     0610617
8     0610618
9     0610621
10    0610622
11    0610623
12    0610601
13    0610602
14    0610603
Name: post_id, dtype: object
0     0000000
1     0731321
2     0731105
3     0731101
4     0731106
5     0731103
6     0731107
7     0731323
8     0782651
9     0731102
10    0000000
11    0730181
12    0731322
Name: post_id, dtype: object
0     0000000
1     0790501
2     0790502
3     0790503
4     0790504
5     0790505
6     0790506
7     0790507
8     0790508
9     0790509
10    0790510
11    0790511
Name: post_id, dtype: object
0     0000000
1     0782121
2     0782122
3     0782123
4     0782124
5     0782111
6     0782112
7     0782101
8     0782102
9     0782103
10    0782104
11    0782105
12    0782106
13    0782107
14    0782108
15    0782109
Name: post_id, dtype: object
0     0000000
1     0782631
2     0782632
3     0782633
4     0782634
5     0000000
6     0782636
7     0782637
8     0782638
9     0782639
10    0782641
11    0782642
Name: post_id, dtype: object
0    0000000
1    0782511
2    0782502
3    0782514
4    0782516
5    0782501
6    0782503
7    0782513
8    0782512
9    0782515
Name: post_id, dtype: object
0     0000000
1     0782201
2     0782224
3     0782205
4     0782213
5     0782211
6     0782214
7     0782212
8     0782204
9     0782222
10    0782223
11    0782225
12    0782203
13    0782221
14    0782206
15    0782202
Name: post_id, dtype: object
0     0000000
1     0711231
2     0711232
3     0711233
4     0711234
5     0711235
6     0711221
7     0711222
8     0711223
9     0711224
10    0711225
11    0711211
12    0711201
13    0711202
14    0711247
15    0711248
16    0711249
17    0711250
18    0711251
19    0711252
20    0711253
21    0711254
22    0711255
23    0711256
24    0711257
25    0711258
26    0711259
27    0711260
28    0711261
29    0711262
30    0711263
31    0711264
32    0711265
33    0711266
34    0711267
Name: post_id, dtype: object
0     0000000
1     0711560
2     0711512
3     0711511
4     0711514
5     0711513
6     0711515
7     0711581
8     0711582
9     0711561
10    0711562
11    0711563
12    0711564
13    0711565
14    0711521
15    0711522
16    0711523
17    0711524
18    0711525
19    0711572
20    0711573
21    0711574
22    0711575
23    0711502
24    0711501
25    0711571
26    0711504
27    0711503
28    0711505
29    0711570
30    0711577
31    0711533
32    0711534
33    0711535
34    0711536
35    0711537
36    0711538
37    0711539
38    0711540
39    0711541
40    0711542
41    0711543
42    0711544
43    0711545
44    0711546
45    0711547
46    0711548
47    0711549
48    0711550
49    0711551
50    0711552
51    0711553
52    0711554
53    0711555
54    0711556
55    0711557
Name: post_id, dtype: object
0     0000000
1     0781333
2     0781332
3     0781341
4     0781331
5     0781337
6     0781334
7     0781335
8     0781313
9     0781303
10    0781314
11    0781304
12    0781324
13    0781315
14    0781305
15    0781316
16    0781306
Name: post_id, dtype: object
0     0000000
1     0780310
2     0780348
3     0780321
4     0780322
5     0780323
6     0780324
7     0780325
8     0780326
9     0780327
10    0780328
11    0780329
12    0780330
13    0780331
14    0780332
15    0780333
16    0780334
17    0780335
18    0780349
19    0780341
20    0780346
21    0780343
22    0780342
23    0780347
24    0780344
25    0780311
26    0780345
Name: post_id, dtype: object
0     0000000
1     0781653
2     0781654
3     0781401
4     0781411
5     0781404
6     0781414
7     0781412
8     0781652
9     0781415
10    0781651
11    0781402
12    0781413
13    0781405
14    0781403
Name: post_id, dtype: object
0     0000000
1     0781761
2     0781752
3     0781721
4     0781744
5     0781732
6     0781711
7     0781775
8     0781733
9     0781712
10    0781722
11    0781762
12    0781701
13    0781741
14    0781772
15    0781731
16    0781774
17    0781771
18    0781742
19    0781773
20    0781743
21    0781763
22    0781751
23    0781753
Name: post_id, dtype: object
0     0000000
1     0711426
2     0711465
3     0711466
4     0711462
5     0711463
6     0711467
7     0711419
8     0711418
9     0711416
10    0711415
11    0711413
12    0711414
13    0711464
14    0711425
15    0711422
16    0711402
17    0711403
18    0711404
19    0711405
20    0711406
21    0711407
22    0711408
23    0711409
24    0711410
25    0711411
26    0711412
27    0711471
28    0711423
29    0711452
30    0711432
31    0711453
32    0711433
33    0711454
34    0711434
35    0711455
36    0711435
37    0711456
38    0711436
39    0711457
40    0711437
41    0711458
42    0711438
43    0711459
44    0711439
45    0711460
46    0711440
47    0711461
48    0711441
49    0711442
50    0711473
51    0711424
52    0711472
53    0711451
54    0711431
Name: post_id, dtype: object
0     0000000
1     0710261
2     0710212
3     0710251
4     0710249
       ...
62    0710232
63    0710208
64    0710351
65    0710478
66    0710352
Name: post_id, Length: 67, dtype: object
0     0000000
1     0710553
2     0710571
3     0710547
4     0710548
       ...
58    0710562
59    0710552
60    0710566
61    0710551
62    0710578
Name: post_id, Length: 63, dtype: object
0     0000000
1     0710770
2     0710755
3     0710733
4     0710733
5     0710762
6     0710704
7     0710751
8     0710734
9     0710734
10    0710731
11    0710754
12    0710732
13    0710732
14    0710732
15    0710732
16    0710737
17    0710705
18    0710706
19    0710707
20    0710761
21    0710735
22    0710771
23    0710772
24    0710773
25    0710774
26    0710775
27    0710776
28    0710777
29    0710778
30    0710779
31    0710780
32    0710781
33    0710726
34    0710742
35    0710742
36    0710711
37    0710711
38    0710753
39    0710714
40    0710752
41    0710736
42    0710736
Name: post_id, dtype: object
0     0000000
1     0000000
2     0792403
3     0792404
4     0792403
5     0792403
6     0792401
7     0792401
8     0792404
9     0792401
10    0792401
11    0792404
12    0792402
13    0792403
14    0792403
15    0792551
16    0792131
17    0792552
18    0792132
19    0792412
20    0792411
Name: post_id, dtype: object
0    0000000
1    0792205
2    0792202
3    0792203
4    0792206
5    0792201
6    0792204
7    0792207
Name: post_id, dtype: object
0     0000000
1     0980126
2     0980121
3     0980113
4     0980103
5     0980133
6     0980112
7     0980125
8     0980114
9     0980102
10    0980122
11    0980135
12    0980132
13    0980123
14    0980134
15    0980101
16    0980115
17    0980104
18    0980111
19    0980124
20    0980131
Name: post_id, dtype: object
0     0000000
1     0980336
2     0980334
3     0980338
4     0980335
5     0980337
6     0980339
7     0980331
8     0980341
9     0980342
10    0980332
11    0980333
Name: post_id, dtype: object
0     0000000
1     0981201
2     0981331
3     0981216
4     0981212
5     0981203
6     0981214
7     0981206
8     0981213
9     0981211
10    0981207
11    0981205
12    0981332
13    0981215
14    0981202
15    0981204
Name: post_id, dtype: object
0     0000000
1     0982201
2     0982362
3     0982230
4     0982220
5     0982363
6     0982361
7     0982238
8     0982204
9     0982206
10    0982227
11    0982367
12    0982214
13    0982368
14    0982202
15    0982211
16    0982208
17    0982365
18    0982252
19    0982241
20    0982251
21    0982242
22    0982243
23    0982253
24    0982212
25    0982231
26    0982221
27    0982232
28    0982222
29    0982233
30    0982223
31    0982234
32    0982224
33    0982225
34    0982236
35    0982226
36    0982205
37    0982207
38    0982364
39    0982235
40    0982366
41    0982213
42    0982203
43    0982237
Name: post_id, dtype: object

0    0000000
1    0982501
2    0982502
Name: post_id, dtype: object
0     0000000
1     0982801
2     0982804
3     0982621
4     0982806
5     0982803
6     0982622
7     0982623
8     0982624
9     0982802
10    0982805
11    0000000
Name: post_id, dtype: object
0     0000000
1     0740413
2     0740424
3     0740744
4     0740415
5     0740423
6     0740743
7     0740403
8     0740742
9     0740422
10    0740747
11    0740402
12    0740412
13    0740414
14    0740425
15    0740426
16    0740427
17    0740746
18    0740421
19    0740404
20    0740401
21    0740745
22    0740411
23    0740741
24    0740405
Name: post_id, dtype: object
0     0000000
1     0770131
2     0770203
3     0770204
4     0770345
5     0770344
6     0770201
7     0770341
8     0770134
9     0770218
10    0770212
11    0000000
12    0770211
13    0770216
14    0770215
15    0770206
16    0770202
17    0770133
18    0770207
19    0770213
20    0770214
21    0770217
22    0770205
23    0770221
24    0770223
25    0770225
26    0770224
27    0770222
28    0770208
Name: post_id, dtype: object
0     0000000
1     0783302
2     0783457
3     0783309
4     0783452
5     0783442
6     0783456
7     0783451
8     0783455
9     0783454
10    0783441
11    0783453
12    0783301
13    0770461
14    0783306
15    0783308
16    0770464
17    0783305
18    0770462
19    0770463
20    0783312
21    0783307
22    0783303
23    0770465
24    0783311
25    0000000
26    0783313
27    0770466
28    0783304
Name: post_id, dtype: object
0     0000000
1     0783711
2     0783634
3     0783712
4     0783713
5     0000000
6     0783636
7     0783633
8     0783637
9     0783621
10    0783702
11    0783638
12    0783715
13    0783701
14    0783716
15    0783632
16    0783635
17    0783717
18    0783541
Name: post_id, dtype: object
0     0000000
1     0784144
2     0784117
3     0784142
4     0784134
5     0784110
6     0784119
7     0784111
8     0784112
9     0784113
10    0784114
11    0784115
12    0784116
13    0784131
14    0784121
15    0784123
16    0784140
17    0784133
18    0784143
19    0784141
20    0784145
21    0784132
22    0000000
23    0783951
24    0783953
25    0783952
26    0783955
27    0783954
28    0784118
29    0784130
30    0784120
31    0784108
32    0784122
33    0784101
34    0784102
35    0784103
36    0784104
37    0784105
38    0784106
39    0784107
40    0783871
Name: post_id, dtype: object
0    0000000
1    0784432
2    0784411
3    0784433
4    0784412
5    0784421
6    0784422
7    0784431
Name: post_id, dtype: object
0     0000000
1     0983531
2     0983532
3     0983533
4     0000000
5     0983541
6     0983511
7     0983521
8     0983502
9     0983503
10    0983542
11    0983522
12    0983512
13    0983523
14    0983534
15    0983543
16    0983504
Name: post_id, dtype: object
0     0000000
1     0983311
2     0983133
3     0983133
4     0983306
5     0983312
6     0983313
7     0983314
8     0983136
9     0983303
10    0983305
11    0983142
12    0983304
13    0983143
14    0983131
15    0983144
16    0983315
17    0983141
18    0983135
19    0983132
20    0983316
21    0983134
22    0983302
23    0983301
Name: post_id, dtype: object
0     0000000
1     0986101
2     0986102
3     0986225
4     0986234
5     0986232
6     0986231
7     0986233
8     0986106
9     0986103
10    0986228
11    0986104
12    0986341
13    0986226
14    0986222
15    0986105
Name: post_id, dtype: object
0     0000000
1     0985741
2     0985744
3     0985754
4     0985701
5     0985725
6     0985743
7     0985751
8     0985711
9     0985712
10    0985713
11    0985714
12    0985765
13    0985739
14    0985752
15    0985703
16    0985753
17    0985761
18    0985705
19    0985704
20    0985742
21    0985745
22    0985702
23    0985702
24    0985703
25    0985701
26    0985763
27    0985717
28    0985734
29    0985762
30    0985738
31    0985721
32    0985722
33    0985723
34    0985755
35    0985764
36    0985761
Name: post_id, dtype: object
0     0000000
1     0985103
2     0985554
3     0985101
4     0985564
5     0985111
6     0985562
7     0985552
8     0985102
9     0985555
10    0985112
11    0985551
12    0985113
13    0985563
14    0985561
15    0985565
16    0985553
Name: post_id, dtype: object
0     0000000
1     0985827
2     0985445
3     0985444
4     0985443
5     0985221
6     0985441
7     0985212
8     0985211
9     0985206
10    0985201
11    0985205
12    0985202
13    0985207
14    0985203
15    0985442
16    0985213
17    0985204
18    0985806
19    0985802
20    0985952
21    0985955
22    0985954
23    0985826
24    0985805
25    0985821
26    0985803
27    0985808
28    0985825
29    0985815
30    0985801
31    0985953
32    0985824
33    0985822
34    0985807
35    0985823
36    0985814
37    0985804
38    0985816
39    0985951
Name: post_id, dtype: object
0     0000000
1     0984462
2     0984455
3     0984103
4     0984138
5     0984110
6     0000000
7     0984132
8     0984456
9     0984451
10    0984141
11    0984104
12    0984136
13    0984466
14    0984140
15    0984137
16    0984135
17    0984467
18    0984134
19    0984139
20    0984116
21    0984111
22    0984112
23    0984113
24    0984114
25    0984115
26    0984457
27    0984131
28    0984121
29    0984122
30    0984123
31    0984124
32    0984125
33    0984126
34    0984101
35    0984464
36    0984465
37    0984106
38    0984105
39    0984133
40    0984461
41    0984463
42    0984102
43    0984107
Name: post_id, dtype: object
0    0000000
1    0971201
2    0000000
3    0971202
Name: post_id, dtype: object
0    0000000
1    0970401
2    0970311
Name: post_id, dtype: object
0    0000000
1    0970101
2    0970211
Name: post_id, dtype: object
0     0000000
1     0983226
2     0982941
3     0983225
4     0983221
5     0983228
6     0982943
7     0982942
8     0983227
9     0983222
10    0983224
11    0983223
12    0983207
13    0983217
14    0983251
15    0983211
16    0983201
17    0983212
18    0983202
19    0983213
20    0983203
21    0983214
22    0983204
23    0983215
24    0983205
25    0983216
26    0983206
Name: post_id, dtype: object
0     0000000
1     0920064
2     0920065
3     0920066
4     0920006
5     0920027
6     0920031
7     0920050
8     0920181
9     0000000
10    0920012
11    0920174
12    0920015
13    0920001
14    0920018
15    0920184
16    0920007
17    0920023
18    0920183
19    0920003
20    0920004
21    0920032
22    0920061
23    0920033
24    0920062
25    0000000
26    0920011
27    0920041
28    0920051
29    0920042
30    0920052
31    0920043
32    0920053
33    0920044
34    0920021
35    0920069
36    0920173
37    0920024
38    0920022
39    0920017
40    0920014
41    0920016
42    0920067
43    0920068
44    0000000
45    0920002
46    0920026
47    0920013
48    0920063
Name: post_id, dtype: object
0     0000000
1     0920361
2     0920234
3     0920205
4     0920231
5     0920355
6     0920233
7     0920206
8     0920222
9     0920352
10    0920225
11    0920235
12    0920356
13    0920232
14    0920357
15    0920221
16    0920203
17    0920224
18    0920214
19    0920211
20    0920213
21    0920362
22    0920358
23    0920207
24    0920216
25    0920217
26    0920218
27    0920354
28    0920353
29    0920351
30    0920236
31    0920223
32    0920212
33    0920201
34    0920215
Name: post_id, dtype: object
0     0000000
1     0994117
2     0994114
3     0994127
4     0994126
5     0994356
6     0994351
7     0994352
8     0994353
9     0994355
10    0994354
11    0994143
12    0994115
13    0994131
14    0994124
15    0994123
16    0994125
17    0994118
18    0994144
19    0994141
20    0994134
21    0994142
22    0994147
23    0994121
24    0994132
25    0994116
26    0994113
27    0994111
28    0994357
29    0994145
30    0994133
31    0994146
32    0994112
33    0994122
34    0994135
Name: post_id, dtype: object
0     0000000
1     0994524
2     0994401
3     0994522
4     0994523
5     0994526
6     0994404
7     0994403
8     0994521
9     0994402
10    0994407
11    0994405
12    0994406
13    0994525
Name: post_id, dtype: object
0     0000000
1     0993616
2     0993603
3     0993613
4     0993611
5     0993601
6     0993612
7     0993451
8     0993615
9     0993452
10    0993602
11    0993453
12    0993604
13    0993642
14    0993614
15    0993605
16    0993641
17    0993454
Name: post_id, dtype: object

0     0000000
1     0991432
2     0991411
3     0991436
4     0991414
5     0991404
6     0991413
7     0991426
8     0991421
9     0991434
10    0991417
11    0991405
12    0991416
13    0991427
14    0991433
15    0991423
16    0991424
17    0991403
18    0991431
19    0991401
20    0991407
21    0991422
22    0991402
23    0991418
24    0991415
25    0991412
26    0991437
27    0991406
28    0991435
29    0991425
Name: post_id, dtype: object
0     0000000
1     0991364
2     0991116
3     0991251
4     0991137
5     0991362
6     0991253
7     0991252
8     0991366
9     0991114
10    0991132
11    0991133
12    0991135
13    0991361
14    0991104
15    0991103
16    0991363
17    0991134
18    0991113
19    0991106
20    0991105
21    0991123
22    0991124
23    0991131
24    0991254
25    0991367
26    0991365
27    0991138
28    0991136
29    0991121
30    0991101
31    0991102
32    0991117
33    0991115
34    0991122
35    0991118
36    0991112
Name: post_id, dtype: object
0     0000000
1     0910553
2     0930502
3     0910557
4     0930505
5     0910473
6     0910556
7     0930503
8     0910472
9     0910471
10    0930508
11    0910558
12    0930506
13    0910552
14    0910555
15    0930421
16    0930424
17    0930504
18    0930423
19    0930507
20    0910554
21    0930422
22    0930501
23    0910551
24    0930532
Name: post_id, dtype: object
0     0000000
1     0990701
2     0990623
3     0990702
4     0990704
       ...
60    0990423
61    0990417
62    0990403
63    0990418
64    0990402
Name: post_id, Length: 65, dtype: object
0     0000000
1     0996402
2     0996321
3     0996503
4     0930732
5     0996504
6     0996501
7     0996415
8     0996325
9     0996323
10    0996322
11    0930651
12    0996404
13    0996506
14    0930652
15    0996271
16    0996412
17    0996326
18    0996329
19    0996327
20    0996328
21    0996414
22    0930733
23    0930731
24    0996411
25    0930734
26    0000000
27    0996505
28    0996403
29    0996401
30    0996509
31    0996508
32    0996507
33    0996272
Name: post_id, dtype: object
0     0000000
1     0995601
2     0995602
3     0995544
4     0995606
5     0995605
6     0995614
7     0995612
8     0995543
9     0995611
10    0995612
11    0995613
12    0995613
13    0995613
14    0995551
15    0995552
16    0995603
17    0995613
18    0995541
19    0995542
20    0995604
21    0995553
Name: post_id, dtype: object
0     0000000
1     0981621
2     0981624
3     0000000
4     0981607
5     0981604
6     0981614
7     0981606
8     0981612
9     0981613
10    0981615
11    0981602
12    0981603
13    0981616
14    0981605
15    0981623
16    0981601
17    0981611
18    0981941
19    0981943
20    0981942
21    0981944
22    0981622
Name: post_id, dtype: object
0     0000000
1     0981424
2     0981504
3     0981421
4     0981505
5     0981423
6     0981422
7     0981503
8     0981506
9     0981501
10    0981502
Name: post_id, dtype: object
0     0000000
1     0981702
2     0981707
3     0981704
4     0981708
5     0981701
6     0981821
7     0981703
8     0981706
9     0981821
10    0981821
11    0981705
Name: post_id, dtype: object
0     0000000
1     0993222
2     0993232
3     0993221
4     0993231
5     0993202
6     0993234
7     0993224
8     0993243
9     0000000
10    0993225
11    0993233
12    0993211
13    0993212
14    0993213
15    0993201
16    0993223
17    0993214
18    0992362
19    0992382
20    0992304
21    0992351
22    0992361
23    0992306
24    0992356
25    0992302
26    0992381
27    0992372
28    0992371
29    0992354
30    0992305
31    0992373
32    0992303
33    0992321
34    0992322
35    0992323
36    0992324
37    0992325
38    0992326
39    0992327
40    0992383
41    0992311
42    0992312
43    0992301
44    0992310
45    0992355
Name: post_id, dtype: object
0     0000000
1     0495412
2     0495332
3     0495413
4     0495407
5     0495414
6     0495404
7     0495411
8     0495408
9     0495406
10    0495405
11    0495331
12    0495415
13    0495416
14    0495403
15    0495402
16    0495401
17    0495333
Name: post_id, dtype: object
0     0000000
1     0520111
2     0520112
3     0520114
4     0520102
5     0520103
6     0520101
7     0520106
8     0000000
9     0520105
10    0520113
11    0520104
12    0520115
13    0520116
Name: post_id, dtype: object
0     0000000
1     0590921
2     0590905
3     0590915
4     0590923
5     0590641
6     0590914
7     0590901
8     0590912
9     0590907
10    0590916
11    0590642
12    0590922
13    0590904
14    0590903
15    0590906
16    0590908
17    0590913
18    0590911
19    0590902
Name: post_id, dtype: object
0     0000000
1     0591606
2     0591746
3     0591622
4     0591602
5     0591741
6     0591752
7     0591744
8     0591601
9     0591743
10    0591749
11    0591751
12    0591748
13    0591612
14    0591754
15    0591623
16    0591615
17    0591621
18    0591614
19    0591747
20    0591753
21    0591745
22    0591624
23    0591604
24    0591742
25    0591611
26    0591616
27    0591605
28    0591603
29    0591625
30    0591613
Name: post_id, dtype: object
0     0000000
1     0495601
2     0495801
3     0495611
4     0495602
5     0495603
6     0495811
7     0495612
8     0495821
9     0495831
10    0495812
11    0495604
12    0000000
13    0495605
14    0495813
15    0495723
16    0495721
17    0495802
18    0495822
19    0495832
20    0495724
21    0495614
22    0495814
23    0495833
24    0495615
25    0495616
Name: post_id, dtype: object
0     0000000
1     0591511
2     0591941
3     0591983
4     0591921
5     0591985
6     0591984
7     0591942
8     0591931
9     0591961
10    0591987
11    0591911
12    0591982
13    0591971
14    0591986
15    0591951
16    0591433
17    0591501
18    0591506
19    0591432
20    0591505
21    0591431
22    0591434
23    0591502
24    0591512
25    0591513
26    0591504
27    0591503
Name: post_id, dtype: object
0     0000000
1     0540031
2     0540001
3     0540011
4     0540012
5     0540021
6     0540002
7     0540063
8     0540015
9     0540023
10    0540052
11    0540004
12    0540003
13    0540005
14    0540013
15    0540022
16    0540064
17    0540032
18    0540051
19    0540211
20    0540362
21    0540143
22    0540201
23    0540202
24    0540141
25    0540364
26    0000000
27    0540203
28    0540142
29    0000000
30    0540204
31    0540361
32    0540041
33    0540016
34    0540042
35    0540061
36    0540014
37    0540062
Name: post_id, dtype: object
0     0000000
1     0592127
2     0592243
3     0592123
4     0592244
5     0592245
6     0592124
7     0552303
8     0552304
9     0592331
10    0552305
11    0552314
12    0552315
13    0550001
14    0550008
15    0550007
16    0550004
17    0550006
18    0550005
19    0592126
20    0592241
21    0000000
22    0552311
23    0552312
24    0552313
25    0550002
26    0592125
27    0550003
28    0552301
29    0552302
30    0552307
31    0552316
32    0592122
33    0592242
34    0552306
35    0592332
36    0592121
37    0552308
38    0552309
Name: post_id, dtype: object
0     0000000
1     0550322
2     0550414
3     0550325
4     0550103
5     0550102
6     0550105
7     0550104
8     0550415
9     0550324
10    0550413
11    0550106
12    0550101
13    0550321
14    0550411
15    0550412
16    0550107
17    0550323
Name: post_id, dtype: object
0     0000000
1     0592414
2     0592404
3     0592423
4     0592422
5     0000000
6     0592427
7     0592251
8     0592424
9     0592341
10    0592412
11    0592343
12    0592413
13    0592402
14    0592418
15    0592426
16    0592344
17    0592252
18    0592417
19    0592416
20    0592403
21    0592401
22    0592415
23    0592425
24    0592342
25    0592421
Name: post_id, dtype: object
0     0000000
1     0570011
2     0593463
3     0570035
4     0570014
5     0570036
6     0570013
7     0593451
8     0570173
9     0570174
10    0570027
11    0570172
12    0570033
13    0570034
14    0570023
15    0570021
16    0570022
17    0570003
18    0570004
19    0570024
20    0593461
21    0570012
22    0593462
23    0570171
24    0570002
25    0593454
26    0570015
27    0570005
28    0570006
29    0570007
30    0000000
31    0593453
32    0570025
33    0570031
34    0570032
35    0570026
Name: post_id, dtype: object

0     0000000
1     0580001
2     0580012
3     0580033
4     0580014
5     0580022
6     0580024
7     0580023
8     0580027
9     0580021
10    0580011
11    0580015
12    0580031
13    0580032
14    0580004
15    0580003
16    0580002
17    0580026
18    0580013
19    0580025
Name: post_id, dtype: object
0     0000000
1     0580202
2     0580342
3     0580421
4     0580203
5     0580207
6     0000000
7     0580343
8     0580343
9     0580201
10    0580201
11    0580201
12    0580201
13    0580341
14    0580206
15    0580204
16    0580422
17    0580205
Name: post_id, dtype: object
0     0000000
1     0560019
2     0560003
3     0560013
4     0592562
5     0560015
6     0560028
7     0560002
8     0592563
9     0560025
10    0560005
11    0560027
12    0560007
13    0560026
14    0560022
15    0560146
16    0560144
17    0592566
18    0560023
19    0560143
20    0560006
21    0592564
22    0560142
23    0560021
24    0592565
25    0560014
26    0560016
27    0560011
28    0560141
29    0560004
30    0560017
31    0000000
32    0560024
33    0560018
34    0592561
35    0593107
36    0593352
37    0593351
38    0593354
39    0593353
40    0593233
41    0593111
42    0593101
43    0593103
44    0592571
45    0593106
46    0593105
47    0593102
48    0593104
49    0593231
50    0593108
51    0593355
52    0593112
53    0593232
Name: post_id, dtype: object
0     0000000
1     0800101
2     0800102
3     0800271
4     0800271
       ...
92    0800333
93    0800331
94    0800317
95    0800318
96    0800316
Name: post_id, Length: 97, dtype: object
0     0000000
1     0801203
2     0801278
3     0801223
4     0801226
       ...
74    0801263
75    0801235
76    0801217
77    0801211
78    0801212
Name: post_id, Length: 79, dtype: object
0    0000000
1    0801406
2    0801407
3    0801408
4    0801404
5    0801405
6    0801403
7    0801402
8    0801401
Name: post_id, dtype: object
0     0000000
1     0810212
2     0810342
3     0810341
4     0810343
5     0810225
6     0810218
7     0810226
8     0810344
9     0810214
10    0810202
11    0810221
12    0810204
13    0810217
14    0810215
15    0810216
16    0810201
17    0810345
18    0810211
19    0810205
20    0810213
21    0810346
22    0810222
23    0810228
24    0810227
25    0810203
26    0810223
27    0810224
Name: post_id, dtype: object
0     0000000
1     0810035
2     0810154
3     0810151
4     0810152
5     0810161
6     0810162
7     0810155
8     0810156
9     0810163
10    0810164
11    0810153
12    0810006
13    0810036
14    0810038
15    0810037
16    0810039
17    0810031
18    0810021
19    0810032
20    0810022
21    0810033
22    0810023
23    0810034
24    0810008
25    0810005
26    0810007
27    0810011
28    0810001
29    0810012
30    0810002
31    0810013
32    0810003
33    0810014
34    0810015
Name: post_id, dtype: object
0     0000000
1     0890355
2     0890243
3     0890135
4     0890134
5     0890133
6     0890132
7     0890131
8     0890124
9     0890123
10    0890122
11    0890121
12    0890241
13    0890103
14    0890102
15    0890356
16    0890101
17    0890242
18    0890136
19    0890125
20    0890357
21    0890351
22    0890352
23    0890353
24    0890371
25    0890372
26    0890373
27    0890374
28    0890375
29    0890376
30    0890377
31    0890378
32    0890361
33    0890362
34    0890363
35    0890354
36    0890137
37    0890138
38    0890111
39    0890112
40    0890113
41    0890114
42    0890115
43    0890116
44    0890117
45    0890118
46    0890126
47    0890127
48    0890104
49    0890105
50    0890106
51    0890107
Name: post_id, dtype: object
0     0000000
1     0820382
2     0820384
3     0820381
4     0820085
       ...
89    0820044
90    0820044
91    0820042
92    0820042
93    0820042
Name: post_id, Length: 94, dtype: object
0     0000000
1     0891330
2     0891310
3     0891371
4     0891364
5     0891365
6     0891363
7     0891366
8     0891354
9     0891355
10    0891362
11    0891367
12    0891325
13    0891313
14    0891352
15    0891356
16    0891353
17    0891331
18    0891311
19    0891332
20    0891312
21    0891351
22    0891341
23    0891321
24    0891342
25    0891322
26    0891343
27    0891323
28    0891344
29    0891324
30    0891345
31    0891374
32    0891368
33    0891372
34    0891373
35    0891361
Name: post_id, dtype: object
0     0000000
1     0891531
2     0891551
3     0891571
4     0891511
5     0000000
6     0891581
7     0891583
8     0891561
9     0891582
10    0891572
11    0891541
12    0891573
13    0000000
14    0891542
15    0891562
16    0891543
17    0891501
18    0891552
19    0891512
20    0891573
21    0891521
22    0891502
23    0891553
24    0891513
25    0891532
26    0891563
27    0891522
Name: post_id, dtype: object
0     0000000
1     0892262
2     0892145
3     0892121
4     0892125
5     0892261
6     0892126
7     0892147
8     0892138
9     0892103
10    0892123
11    0892111
12    0892137
13    0892151
14    0892117
15    0892271
16    0892272
17    0892146
18    0892154
19    0892140
20    0892106
21    0892114
22    0892136
23    0892272
24    0891881
25    0892105
26    0892273
27    0892273
28    0892263
29    0892261
30    0892101
31    0892261
32    0892122
33    0892104
34    0892133
35    0892152
36    0892116
37    0891882
38    0892134
39    0892124
40    0892115
41    0892132
42    0892127
43    0892107
44    0892131
45    0892148
46    0892155
47    0892135
48    0892153
49    0892113
50    0892112
51    0892102
52    0892156
53    0892141
54    0892142
55    0892143
Name: post_id, dtype: object
0     0000000
1     0892771
2     0892772
3     0892604
4     0892605
5     0892445
6     0892448
7     0892447
8     0892622
9     0892621
10    0892447
11    0892447
12    0892632
13    0892631
14    0892616
15    0892775
16    0892447
17    0892455
18    0892624
19    0892623
20    0892626
21    0892625
22    0892611
23    0892612
24    0892613
25    0892614
26    0892561
27    0892563
28    0892562
29    0892564
30    0892601
31    0892602
32    0892603
33    0892776
34    0892633
35    0892634
36    0892615
37    0892628
38    0892627
39    0892773
40    0892636
41    0892635
42    0892637
43    0892638
44    0892446
45    0892774
Name: post_id, dtype: object
0     0000000
1     0890621
2     0890612
3     0890602
4     0890624
       ...
74    0890614
75    0890615
76    0000000
77    0890603
78    0890571
Name: post_id, Length: 79, dtype: object
0     0000000
1     0830044
2     0830001
3     0830090
4     0830020
5     0893151
6     0830041
7     0830002
8     0830003
9     0830004
10    0830047
11    0893152
12    0893153
13    0830042
14    0830046
15    0893156
16    0830032
17    0830031
18    0830033
19    0830034
20    0830045
21    0830043
22    0830021
23    0830022
24    0830023
25    0893154
26    0830091
27    0830092
28    0893155
Name: post_id, dtype: object
0     0000000
1     0895306
2     0895241
3     0895304
4     0895465
5     0895463
6     0895462
7     0895464
8     0895461
9     0895305
10    0895307
11    0895234
12    0895235
13    0895466
14    0895301
15    0895244
16    0895243
17    0895246
18    0895232
19    0895231
20    0895233
21    0895309
22    0895303
23    0895242
24    0895247
25    0895315
26    0895313
27    0895311
28    0895314
29    0895312
30    0895308
31    0895302
32    0895245
Name: post_id, dtype: object
0     0000000
1     0893676
2     0893332
3     0000000
4     0893662
5     0893283
6     0893307
7     0893311
8     0893666
9     0893321
10    0893321
11    0893334
12    0893305
13    0893665
14    0893303
15    0893322
16    0893304
17    0893674
18    0893324
19    0893334
20    0893663
21    0893664
22    0893306
23    0893331
24    0893675
25    0000000
26    0893443
27    0893443
28    0893443
29    0893673
30    0893301
31    0893302
32    0893661
33    0893284
34    0000000
35    0893326
36    0893323
37    0893442
38    0893442
39    0893442
40    0893442
41    0893671
42    0893312
43    0893314
44    0893313
45    0893333
46    0893308
47    0893282
48    0893281
Name: post_id, dtype: object
0     0000000
1     0893708
2     0893721
3     0893724
4     0000000
5     0894252
6     0893961
7     0893962
8     0894142
9     0894141
10    0893963
11    0893701
12    0893702
13    0893703
14    0893704
15    0893705
16    0893706
17    0893874
18    0893726
19    0893727
20    0893718
21    0893732
22    0893707
23    0894143
24    0893722
25    0893734
26    0893723
27    0000000
28    0893733
29    0893735
30    0893725
31    0893711
32    0893712
33    0893713
34    0893714
35    0893715
36    0893716
37    0893717
38    0893872
39    0893871
40    0893964
41    0000000
42    0893965
43    0893966
44    0893736
Name: post_id, dtype: object

0     0000000
1     0894324
2     0894301
3     0894315
4     0894321
5     0894342
6     0894308
7     0894353
8     0894331
9     0894345
10    0894313
11    0894312
12    0894304
13    0894351
14    0894262
15    0894316
16    0894307
17    0894337
18    0894303
19    0894355
20    0894333
21    0894322
22    0894323
23    0894332
24    0894357
25    0894341
26    0894261
27    0894305
28    0894335
29    0894344
30    0894354
31    0894334
32    0894314
33    0894311
34    0894352
35    0894346
36    0894326
37    0894343
38    0894325
39    0894306
40    0894336
41    0894356
42    0894302
Name: post_id, dtype: object
0     0000000
1     0895551
2     0893576
3     0895546
4     0895865
       ...
59    0895605
60    0895617
61    0895545
62    0895541
63    0895632
Name: post_id, Length: 64, dtype: object
0     0000000
1     0880616
2     0852271
3     0882154
4     0882155
5     0880626
6     0880621
7     0882143
8     0880601
9     0880612
10    0880625
11    0880622
12    0880609
13    0880623
14    0880614
15    0852272
16    0852273
17    0880624
18    0000000
19    0880833
20    0880835
21    0880834
22    0880831
23    0880832
24    0880608
25    0882141
26    0880606
27    0880628
28    0880627
29    0882142
30    0882145
31    0882156
32    0880607
33    0880618
34    0880611
35    0882144
36    0882148
37    0882147
38    0882146
39    0882152
40    0880604
41    0880605
42    0880602
43    0880603
44    0880617
45    0882140
46    0882153
47    0880615
48    0882151
49    0880613
50    0882157
Name: post_id, dtype: object
0     0000000
1     0881113
2     0881112
3     0881101
4     0881131
5     0881133
6     0881132
7     0881134
8     0881130
9     0881135
10    0881141
11    0881142
12    0881143
13    0881144
14    0881145
15    0881146
16    0881147
17    0881148
18    0881149
19    0881136
20    0880876
21    0881117
22    0880873
23    0880871
24    0881137
25    0880771
26    0881101
27    0881129
28    0881103
29    0881139
30    0881140
31    0881125
32    0881151
33    0881119
34    0881138
35    0881104
36    0881101
37    0881108
38    0881106
39    0881102
40    0881107
41    0880875
42    0881389
43    0881115
44    0880877
45    0881101
46    0881101
47    0881111
48    0881116
49    0881105
50    0881128
51    0881124
52    0000000
53    0881120
54    0880872
55    0880878
56    0881118
57    0881118
58    0881101
59    0881114
Name: post_id, dtype: object
0     0000000
1     0881406
2     0881403
3     0881646
4     0881641
       ...
68    0881535
69    0881402
70    0881304
71    0881306
72    0881534
Name: post_id, Length: 73, dtype: object
0     0000000
1     0882301
2     0882305
3     0882271
4     0882272
       ...
57    0882302
58    0882304
59    0882338
60    0882324
61    0882336
Name: post_id, Length: 62, dtype: object
0     0000000
1     0883204
2     0883463
3     0883461
4     0883461
5     0883351
6     0883212
7     0883226
8     0883228
9     0883227
10    0883462
11    0883465
12    0883341
13    0883341
14    0883351
15    0883214
16    0883351
17    0883213
18    0883332
19    0883332
20    0883464
21    0883202
22    0883351
23    0883211
24    0883222
25    0883221
26    0883221
27    0883223
28    0883331
29    0883331
30    0883224
31    0883201
32    0883215
33    0883271
34    0883225
35    0883203
Name: post_id, dtype: object
0     0000000
1     0851146
2     0851145
3     0851132
4     0851212
5     0851133
6     0851262
7     0851211
8     0851144
9     0851131
10    0851206
11    0851203
12    0851204
13    0851201
14    0851261
15    0000000
16    0851207
17    0851202
18    0851205
19    0851143
20    0851147
21    0851142
22    0851141
23    0851213
24    0851134
Name: post_id, dtype: object
0     0000000
1     0880585
2     0880353
3     0880341
4     0880353
       ...
80    0880304
81    0880352
82    0880343
83    0880343
84    0880351
Name: post_id, Length: 85, dtype: object
0     0000000
1     0882578
2     0860213
3     0861641
4     0861644
5     0861642
6     0861643
7     0882725
8     0882722
9     0882724
10    0882721
11    0882723
12    0860131
13    0882601
14    0000000
15    0860657
16    0860654
17    0860653
18    0860651
19    0860652
20    0860345
21    0860342
22    0860343
23    0860344
24    0860341
25    0882576
26    0882566
27    0882561
28    0882565
29    0882562
30    0882563
31    0882564
32    0882572
33    0882571
34    0882574
35    0882573
36    0882575
37    0861645
38    0860523
39    0860216
40    0860202
41    0860215
42    0860211
43    0860204
44    0860212
45    0860205
46    0860203
47    0860214
48    0860201
49    0882602
50    0860522
51    0860656
52    0000000
Name: post_id, dtype: object
0      0000000
1      0861159
2      0861135
3      0861142
4      0861141
        ...
139    0861150
140    0861146
141    0861271
142    0882684
143    0861160
Name: post_id, Length: 144, dtype: object
0     0000000
1     0861602
2     0861451
3     0861631
4     0861632
5     0861633
6     0861634
7     0861635
8     0861636
9     0861637
10    0861638
11    0861639
12    0861630
13    0861732
14    0861731
15    0861733
16    0000000
17    0861625
18    0861621
19    0861623
20    0861626
21    0861601
22    0861651
23    0861652
24    0861653
25    0861654
26    0861655
27    0861656
28    0861657
29    0861658
Name: post_id, dtype: object
0     0000000
1     0861806
2     0861842
3     0861815
4     0861843
5     0861804
6     0861813
7     0861816
8     0861805
9     0861812
10    0861823
11    0861801
12    0861811
13    0861802
14    0861836
15    0861831
16    0861803
17    0861832
18    0000000
19    0861833
20    0861835
21    0861814
22    0861821
23    0861751
24    0861841
25    0861822
26    0861834
Name: post_id, dtype: object
0      0000000
1      0300846
2      0300811
3      0300956
4      0300851
        ...
157    0380012
158    0300923
159    0300132
160    0300125
161    0301271
Name: post_id, Length: 162, dtype: object
0      0000000
1      0361516
2      0368246
3      0383615
4      0368062
        ...
280    0368333
281    0368255
282    0368087
283    0368368
284    0368021
Name: post_id, Length: 285, dtype: object
0      0000000
1      0310804
2      0310824
3      0310055
4      0310013
        ...
105    0310045
106    0310038
107    0391105
108    0310086
109    0310001
Name: post_id, Length: 110, dtype: object
0      0000000
1      0360516
2      0360325
3      0360537
4      0360321
        ...
103    0360364
104    0360361
105    0360368
106    0360311
107    0360375
Name: post_id, Length: 108, dtype: object
0     0000000
1     0370401
2     0370613
3     0370062
4     0370052
       ...
90    0370073
91    0370051
92    0370013
93    0370069
94    0370405
Name: post_id, Length: 95, dtype: object
0     0000000
1     0340071
2     0340005
3     0340011
4     0340101
       ...
58    0340037
59    0340107
60    0340212
61    0340002
62    0340003
Name: post_id, Length: 63, dtype: object
0     0000000
1     0330166
2     0330101
3     0330153
4     0330131
5     0330134
6     0330041
7     0330021
8     0330104
9     0330053
10    0330063
11    0330162
12    0330011
13    0330042
14    0330031
15    0330155
16    0330113
17    0330103
18    0330133
19    0330023
20    0330062
21    0330105
22    0330102
23    0330165
24    0330001
25    0330043
26    0330163
27    0330167
28    0330061
29    0330024
30    0330034
31    0330154
32    0330012
33    0330152
34    0330051
35    0330044
36    0330112
37    0330123
38    0330052
39    0330143
40    0330037
41    0330035
42    0330142
43    0330022
44    0330032
45    0330141
46    0330036
47    0330151
48    0330033
49    0330111
50    0330045
51    0330164
52    0330161
53    0330132
Name: post_id, dtype: object
0     0000000
1     0350044
2     0350076
3     0350079
4     0350092
       ...
76    0395325
77    0395324
78    0395334
79    0395327
80    0395331
Name: post_id, Length: 81, dtype: object
0     0000000
1     0370102
2     0370101
3     0370109
4     0370104
       ...
91    0382817
92    0382814
93    0382813
94    0382816
95    0382815
Name: post_id, Length: 96, dtype: object
0      0000000
1      0360112
2      0360112
3      0360112
4      0360112
        ...
353    0360241
354    0360241
355    0360241
356    0360241
357    0360154
Name: post_id, Length: 358, dtype: object

0     0000000
1     0393312
2     0393364
3     0393382
4     0393352
5     0393343
6     0393342
7     0393321
8     0393332
9     0393302
10    0393351
11    0393353
12    0393372
13    0393371
14    0393373
15    0393313
16    0393331
17    0393303
18    0393301
19    0393315
20    0393311
21    0393361
22    0393362
23    0393333
24    0393381
25    0393314
26    0393341
27    0393363
Name: post_id, dtype: object
0     0000000
1     0301502
2     0301505
3     0301512
4     0301515
5     0301514
6     0301504
7     0301501
8     0301513
9     0301503
10    0301511
Name: post_id, dtype: object
0    0000000
1    0301212
2    0301203
3    0301202
4    0301214
5    0301213
6    0301201
7    0301211
Name: post_id, dtype: object
0     0000000
1     0301309
2     0301303
3     0301301
4     0301307
5     0301305
6     0301311
7     0301302
8     0301304
9     0301306
10    0301308
11    0301402
12    0301405
13    0301416
14    0301413
15    0301411
16    0301412
17    0301415
18    0301403
19    0301404
20    0301732
21    0301719
22    0301724
23    0301722
24    0301717
25    0301712
26    0301711
27    0301727
28    0301720
29    0301729
30    0301716
31    0301733
32    0301711
33    0301728
34    0301718
35    0301715
36    0301737
37    0301714
38    0301725
39    0301731
40    0301721
41    0301734
42    0301735
43    0301723
44    0301736
45    0301713
46    0301726
Name: post_id, dtype: object
0     0000000
1     0382731
2     0382714
3     0382742
4     0382735
5     0382724
6     0382701
7     0382754
8     0382722
9     0382703
10    0382745
11    0382702
12    0382733
13    0382751
14    0382725
15    0382743
16    0382711
17    0382712
18    0382752
19    0382741
20    0382715
21    0382732
22    0382723
23    0382721
24    0382746
25    0382753
26    0382761
27    0382713
28    0382705
29    0382734
30    0382704
31    0382747
32    0382744
Name: post_id, dtype: object
0     0000000
1     0382502
2     0382202
3     0382413
4     0382208
5     0382411
6     0382323
7     0382504
8     0382207
9     0382201
10    0382203
11    0382503
12    0382505
13    0382322
14    0382326
15    0382412
16    0382204
17    0382321
18    0382324
19    0382327
20    0382206
21    0382205
22    0382501
23    0382325
Name: post_id, dtype: object
0    0000000
1    0361422
2    0361424
3    0361414
4    0361412
5    0361423
6    0361413
7    0361411
8    0361421
9    0361415
Name: post_id, dtype: object
0     0000000
1     0383837
2     0383833
3     0381203
4     0383804
5     0381206
6     0383812
7     0383805
8     0381216
9     0383836
10    0383835
11    0381214
12    0381213
13    0381202
14    0383811
15    0383831
16    0383803
17    0383834
18    0383806
19    0381211
20    0381201
21    0383801
22    0383802
23    0381207
24    0381204
25    0383814
26    0381212
27    0383813
28    0381205
29    0383832
30    0381215
Name: post_id, dtype: object
0     0000000
1     0380233
2     0380211
3     0380204
4     0380212
5     0380203
6     0380241
7     0380223
8     0380231
9     0380202
10    0380201
11    0380221
12    0380243
13    0380222
14    0380232
15    0380242
Name: post_id, dtype: object
0     0000000
1     0381142
2     0381113
3     0381104
4     0381133
5     0381131
6     0381123
7     0381141
8     0381143
9     0381103
10    0381132
11    0381111
12    0381112
13    0381145
14    0381101
15    0381102
16    0381134
17    0381121
18    0381122
19    0381144
Name: post_id, dtype: object
0     0000000
1     0383683
2     0383651
3     0383682
4     0383685
5     0383662
6     0383642
7     0383635
8     0383671
9     0383632
10    0383633
11    0383636
12    0383673
13    0383621
14    0383684
15    0383623
16    0383634
17    0383624
18    0383625
19    0383645
20    0383643
21    0383681
22    0383672
23    0383641
24    0383661
25    0383631
26    0383622
27    0383644
Name: post_id, dtype: object
0     0000000
1     0383501
2     0383513
3     0383541
4     0383531
5     0383523
6     0383502
7     0383524
8     0383521
9     0383512
10    0383525
11    0383503
12    0383522
13    0383514
14    0383532
15    0383542
16    0383543
17    0383515
18    0383511
Name: post_id, dtype: object
0     0000000
1     0370316
2     0370301
3     0370302
4     0370311
5     0370304
6     0370512
7     0370523
8     0370541
9     0370534
10    0370542
11    0370535
12    0370521
13    0370522
14    0370525
15    0370538
16    0370533
17    0370511
18    0370531
19    0370536
20    0370532
21    0370514
22    0370537
23    0370543
24    0301701
25    0370524
26    0370513
27    0370303
28    0370318
29    0370313
30    0370315
31    0370312
32    0370305
33    0370317
34    0370309
35    0370314
36    0370308
37    0370306
38    0370307
Name: post_id, dtype: object
0     0000000
1     0393116
2     0393108
3     0393105
4     0393178
       ...
81    0393129
82    0393175
83    0393175
84    0393148
85    0393102
Name: post_id, Length: 86, dtype: object
0      0000000
1      0392501
2      0392534
3      0392543
4      0392816
        ...
172    0392547
173    0392717
174    0392559
175    0392589
176    0392588
Name: post_id, Length: 177, dtype: object
0     0000000
1     0000000
2     0330071
3     0330071
4     0330071
5     0330071
6     0330071
7     0330071
8     0330071
9     0330071
10    0330071
11    0330071
12    0330071
13    0330071
14    0330071
15    0330071
16    0330071
17    0330071
18    0330071
19    0330071
20    0330071
21    0330071
22    0000000
23    0330072
24    0330072
25    0330073
26    0392311
27    0392314
28    0330074
29    0392312
30    0392313
31    0392315
Name: post_id, dtype: object
0     0000000
1     0394106
2     0394113
3     0394115
4     0394112
5     0394111
6     0394131
7     0394142
8     0394123
9     0394124
10    0394103
11    0394137
12    0394104
13    0394133
14    0394132
15    0394138
16    0394145
17    0394152
18    0394155
19    0394122
20    0394116
21    0394105
22    0394117
23    0394144
24    0394102
25    0394101
26    0394135
27    0394134
28    0394121
29    0394156
30    0394157
31    0394153
32    0394114
33    0394141
34    0394154
35    0394151
36    0394143
37    0394136
Name: post_id, dtype: object
0      0000000
1      0392657
2      0392604
3      0392406
4      0392407
        ...
116    0392604
117    0392604
118    0392603
119    0392623
120    0392633
Name: post_id, Length: 121, dtype: object
0    0000000
1    0393212
2    0393215
3    0393213
4    0393211
5    0394301
6    0393214
Name: post_id, dtype: object
0     0000000
1     0392189
2     0392147
3     0392116
4     0392141
       ...
83    0392152
84    0392158
85    0392153
86    0392236
87    0392188
Name: post_id, Length: 88, dtype: object
0    0000000
1    0394601
2    0394602
Name: post_id, dtype: object
0     0000000
1     0350113
2     0350001
3     0394223
4     0000000
5     0350104
6     0350104
7     0394221
8     0350112
9     0394224
10    0350111
11    0394222
12    0350005
13    0000000
14    0350003
15    0350002
Name: post_id, dtype: object
0    0000000
1    0394502
2    0394501
3    0394503
Name: post_id, dtype: object
0    0000000
1    0394711
2    0394712
Name: post_id, dtype: object
0     0000000
1     0390111
2     0390112
3     0390453
4     0390141
5     0390143
6     0390142
7     0390132
8     0390451
9     0390134
10    0390122
11    0390121
12    0390452
13    0390133
14    0390131
15    0390144
16    0390113
17    0390135
Name: post_id, dtype: object
0      0000000
1      0391508
2      0391508
3      0391561
4      0391528
        ...
159    0391563
160    0391558
161    0391569
162    0391559
163    0391564
Name: post_id, Length: 164, dtype: object
0    0000000
1    0390312
2    0390316
3    0390202
4    0390201
5    0390314
6    0390315
7    0390311
8    0390313
9    0390317
Name: post_id, dtype: object
0     0000000
1     0000000
2     0390606
3     0390606
4     0390606
5     0390606
6     0390606
7     0390102
8     0390103
9     0390105
10    0390801
11    0390812
12    0390501
13    0390612
14    0390805
15    0390814
16    0390104
17    0390502
18    0390813
19    0390503
20    0390507
21    0390804
22    0390101
23    0390504
24    0390611
25    0390802
26    0390505
27    0390614
28    0390815
29    0390506
30    0390811
31    0390803
32    0390613
Name: post_id, dtype: object

0     0000000
1     0391202
2     0391207
3     0391212
4     0391211
5     0391206
6     0391208
7     0391201
8     0391203
9     0391205
10    0391204
Name: post_id, dtype: object
0    0000000
1    0391802
2    0391801
Name: post_id, dtype: object
0      0000000
1      0200133
2      0200801
3      0200014
4      0200013
        ...
159    0200844
160    0200843
161    0200845
162    0200846
163    0200886
Name: post_id, Length: 164, dtype: object
0      0000000
1      0270202
2      0270092
3      0270086
4      0270062
        ...
150    0270004
151    0270045
152    0282105
153    0270075
154    0270026
Name: post_id, Length: 155, dtype: object
0     0000000
1     0220007
2     0220004
3     0220002
4     0220003
5     0220101
6     0220102
7     0220211
8     0220006
9     0220005
10    0220001
Name: post_id, dtype: object
0      0000000
1      0250067
2      0250088
3      0250071
4      0250095
        ...
160    0250044
161    0250304
162    0250136
163    0250072
164    0250097
Name: post_id, Length: 165, dtype: object
0     0000000
1     0240051
2     0240031
3     0240081
4     0240001
       ...
62    0240332
63    0240333
64    0240334
65    0240324
66    0240331
Name: post_id, Length: 67, dtype: object
0     0000000
1     0280014
2     0280063
3     0288111
4     0280034
5     0280091
6     0280083
7     0280041
8     0280054
9     0280051
10    0280082
11    0280013
12    0280015
13    0280071
14    0280024
15    0287801
16    0280035
17    0280065
18    0280023
19    0280053
20    0280055
21    0280022
22    0280061
23    0280032
24    0280031
25    0280066
26    0280056
27    0280001
28    0280012
29    0280081
30    0280062
31    0280033
32    0280052
33    0280011
34    0280021
35    0288712
36    0288602
37    0288713
38    0288711
39    0288603
40    0288604
41    0288601
42    0288605
43    0288521
44    0280064
Name: post_id, dtype: object
0     0000000
1     0280503
2     0280502
3     0280501
4     0280533
5     0280532
6     0280531
7     0280534
8     0280511
9     0280481
10    0280517
11    0280776
12    0280771
13    0280775
14    0280773
15    0280772
16    0280774
17    0280516
18    0280521
19    0280526
20    0280522
21    0280524
22    0280527
23    0280523
24    0280662
25    0280661
26    0280663
27    0280664
28    0280554
29    0280553
30    0280555
31    0280551
32    0280552
33    0280514
34    0280542
35    0280512
36    0280513
37    0280515
38    0280543
39    0280545
40    0280541
41    0280544
42    0280302
43    0280301
44    0280303
45    0280304
46    0280305
47    0280525
Name: post_id, dtype: object
0      0000000
1      0210853
2      0210031
3      0210041
4      0210864
        ...
165    0210025
166    0210011
167    0210805
168    0210815
169    0210014
Name: post_id, Length: 170, dtype: object
0    0000000
1    0292207
2    0292204
3    0292205
4    0292203
5    0292208
6    0292201
7    0292202
8    0292206
Name: post_id, dtype: object
0     0000000
1     0260012
2     0260301
3     0260003
4     0260022
5     0260002
6     0260024
7     0260025
8     0260302
9     0260055
10    0260026
11    0260041
12    0260412
13    0260042
14    0260045
15    0260052
16    0260033
17    0260046
18    0260053
19    0260015
20    0260043
21    0260031
22    0260044
23    0260021
24    0260032
25    0260023
26    0000000
27    0260061
28    0260034
29    0260054
30    0260303
31    0260411
32    0260013
33    0260014
34    0260001
35    0260005
36    0260004
37    0260011
38    0260035
39    0260304
40    0260051
Name: post_id, dtype: object
0      0000000
1      0286723
2      0286103
3      0285713
4      0286108
        ...
150    0285712
151    0286101
152    0286722
153    0286105
154    0286104
Name: post_id, Length: 155, dtype: object
0      0000000
1      0287619
2      0287635
3      0287526
4      0287554
        ...
119    0287512
120    0287522
121    0287524
122    0287634
123    0287636
Name: post_id, Length: 124, dtype: object
0      0000000
1      0230402
2      0230401
3      0230403
4      0231761
        ...
412    0230042
413    0230852
414    0230801
415    0230893
416    0230864
Name: post_id, Length: 417, dtype: object
0      0000000
1      0200633
2      0200604
3      0200618
4      0200685
        ...
135    0200634
136    0200612
137    0200609
138    0200607
139    0200617
Name: post_id, Length: 140, dtype: object
0     0000000
1     0200502
2     0200546
3     0200583
4     0200574
5     0200581
6     0200544
7     0200559
8     0200555
9     0200557
10    0200538
11    0200537
12    0200539
13    0200530
14    0200534
15    0200517
16    0200525
17    0200535
18    0200551
19    0200512
20    0200513
21    0200522
22    0200558
23    0200553
24    0200552
25    0200515
26    0200528
27    0200529
28    0200520
29    0200541
30    0200521
31    0200543
32    0200571
33    0200524
34    0200505
35    0200504
36    0200527
37    0200511
38    0200585
39    0200556
40    0200503
41    0200501
42    0200572
43    0200584
44    0200506
45    0200523
46    0200514
47    0200582
48    0200536
49    0200533
50    0200532
51    0200547
52    0200554
53    0200531
54    0200507
55    0200542
56    0200573
57    0200545
Name: post_id, dtype: object
0    0000000
1    0285403
2    0000000
3    0285401
Name: post_id, dtype: object
0     0000000
1     0284307
2     0284421
3     0284303
4     0284211
5     0284305
6     0284424
7     0284426
8     0284304
9     0284302
10    0284423
11    0284301
12    0284425
13    0284422
14    0284306
Name: post_id, dtype: object
0     0000000
1     0283533
2     0283451
3     0283311
4     0283312
5     0283321
6     0283314
7     0283452
8     0283441
9     0283443
10    0283323
11    0283536
12    0283309
13    0283325
14    0283303
15    0283444
16    0283307
17    0283316
18    0283446
19    0283318
20    0283302
21    0283453
22    0283535
23    0283322
24    0283301
25    0283326
26    0283324
27    0283315
28    0283305
29    0283310
30    0283306
31    0283308
32    0283304
33    0283532
34    0283313
35    0283442
36    0283445
37    0283317
38    0283447
39    0283534
40    0283531
41    0283448
Name: post_id, dtype: object
0     0000000
1     0283605
2     0283611
3     0283609
4     0283626
5     0283618
6     0283617
7     0283622
8     0283608
9     0283624
10    0283613
11    0283623
12    0283607
13    0283612
14    0283616
15    0283601
16    0283606
17    0283603
18    0283604
19    0283621
20    0283602
21    0283614
22    0283615
23    0283625
24    0200891
25    0283627
Name: post_id, dtype: object
0     0000000
1     0295503
2     0295511
3     0295523
4     0295507
5     0295521
6     0295513
7     0295523
8     0295502
9     0295512
10    0295513
11    0295521
12    0295501
13    0295616
14    0295614
15    0295612
16    0295703
17    0295701
18    0295621
19    0295615
20    0295611
21    0295617
22    0295619
23    0295613
24    0295618
25    0295702
26    0295523
27    0295502
28    0295503
29    0295501
30    0295523
31    0000000
32    0240341
33    0240341
34    0240341
35    0295522
36    0295504
37    0295502
38    0295522
39    0295522
40    0295523
41    0295513
42    0295503
43    0295513
44    0295513
45    0295523
46    0295514
47    0295503
48    0295506
49    0295505
50    0295523
51    0295513
Name: post_id, dtype: object
0    0000000
1    0294505
2    0294504
3    0294503
4    0294502
5    0294501
Name: post_id, dtype: object
0    0000000
1    0294101
2    0294102
Name: post_id, dtype: object
0    0000000
1    0292501
2    0292502
3    0292311
Name: post_id, dtype: object
0     0000000
1     0281102
2     0281105
3     0281131
4     0281112
5     0281132
6     0281133
7     0281115
8     0281101
9     0281121
10    0281114
11    0281122
12    0281111
13    0281104
14    0281117
15    0281113
16    0281116
17    0281103
Name: post_id, dtype: object
0     0000000
1     0281303
2     0281352
3     0281301
4     0281311
5     0281361
6     0281342
7     0281331
8     0281333
9     0281343
10    0281332
11    0281302
12    0281351
13    0281341
14    0281371
15    0281321
Name: post_id, dtype: object
0     0000000
1     0282231
2     0270611
3     0285642
4     0270508
5     0270501
6     0282232
7     0270502
8     0270421
9     0285641
10    0000000
11    0285633
12    0285633
13    0285633
14    0270505
15    0270503
16    0270504
17    0270506
18    0270423
19    0270422
20    0270507
21    0270424
22    0285643
Name: post_id, dtype: object

0     0000000
1     0288402
2     0288401
3     0288401
4     0288405
5     0288401
6     0288401
7     0288401
8     0288401
9     0288401
10    0288407
11    0288402
12    0288405
13    0288406
14    0288404
15    0288407
16    0288401
17    0288401
18    0288401
19    0288401
20    0288401
21    0288407
22    0288402
23    0288406
24    0288401
25    0288406
26    0288401
27    0288401
28    0288401
29    0288401
30    0288405
31    0288401
32    0288401
33    0288405
34    0288404
35    0288401
36    0288405
37    0288406
38    0288406
39    0288403
40    0288407
Name: post_id, dtype: object
0     0000000
1     0288366
2     0288365
3     0288343
4     0288362
5     0288331
6     0288345
7     0288368
8     0288352
9     0288361
10    0288353
11    0288312
12    0288303
13    0288351
14    0288311
15    0288313
16    0288336
17    0288322
18    0288332
19    0288323
20    0288334
21    0288344
22    0288321
23    0288367
24    0288301
25    0288335
26    0288302
27    0288364
28    0288341
29    0288363
30    0288333
31    0288342
Name: post_id, dtype: object
0     0000000
1     0286223
2     0286301
3     0286302
4     0286303
5     0286411
6     0286222
7     0286304
8     0286221
9     0286412
10    0286413
Name: post_id, dtype: object
0    0000000
1    0288202
2    0288201
Name: post_id, dtype: object
0    0000000
1    0286501
2    0286502
3    0286505
4    0286503
5    0286611
6    0286504
7    0286612
8    0286506
9    0286507
Name: post_id, dtype: object
0    0000000
1    0288803
2    0287905
3    0288802
4    0287904
5    0288801
6    0288804
7    0000000
8    0287906
9    0288805
Name: post_id, dtype: object
0     0000000
1     0285222
2     0285304
3     0285312
4     0285316
5     0285131
6     0285134
7     0285303
8     0285223
9     0285311
10    0285221
11    0285132
12    0285301
13    0285305
14    0285313
15    0285306
16    0000000
17    0285314
18    0285315
19    0285224
20    0285302
Name: post_id, dtype: object
0      0000000
1      9810916
2      9800856
3      9893211
4      9810963
        ...
175    9893215
176    9820263
177    9810967
178    9893205
179    9893206
Name: post_id, Length: 180, dtype: object
0     0000000
1     9830832
2     9830047
3     9830012
4     9830821
       ...
70    0000000
71    9830041
72    9830045
73    9830044
74    9830865
Name: post_id, Length: 75, dtype: object
0     0000000
1     9840032
2     9840030
3     9840039
4     9840033
       ...
79    9840013
80    9840003
81    9840012
82    9840014
83    9840826
Name: post_id, Length: 84, dtype: object
0     0000000
1     9820834
2     9820242
3     9820243
4     9820244
       ...
78    9820813
79    9820213
80    9820818
81    9820816
82    9820822
Name: post_id, Length: 83, dtype: object
0     0000000
1     9813115
2     9813101
3     9813206
4     9818004
5     9813201
6     9813133
7     9813126
8     9813117
9     9813104
10    9813137
11    9813216
12    9813134
13    9813121
14    9813122
15    9813202
16    9813215
17    9818006
18    9813102
19    9813217
20    9813132
21    9813136
22    9813108
23    9813222
24    9813223
25    9813116
26    9813203
27    9813212
28    9813211
29    9813109
30    9813204
31    9813105
32    9813131
33    9818003
34    9818001
35    9818002
36    9813224
37    9813218
38    9818007
39    9813221
40    9813124
41    9818005
42    9813225
43    9813123
44    9813226
45    9813106
46    9813107
47    9813111
48    9813113
49    9813125
50    9813213
51    9813205
52    9813112
53    9813135
54    9813214
55    9813103
56    9813114
Name: post_id, dtype: object
0      0000000
1      9860101
2      9860866
3      9860862
4      9860869
        ...
194    9862404
195    9860867
196    9862135
197    9862121
198    9871102
Name: post_id, Length: 199, dtype: object
0     0000000
1     9850082
2     9850055
3     9850026
4     9850012
       ...
60    9850053
61    9850073
62    9850051
63    9850065
64    9850052
Name: post_id, Length: 65, dtype: object
0      0000000
1      9880182
2      9880105
3      9880172
4      9880174
        ...
361    9880632
362    9880863
363    9880865
364    9880833
365    9880827
Name: post_id, Length: 366, dtype: object
0     0000000
1     9890223
2     9890228
3     9890267
4     9890254
       ...
70    9890256
71    9890275
72    9890263
73    9890242
74    9890257
Name: post_id, Length: 75, dtype: object
0     0000000
1     9811230
2     9811225
3     9811226
4     9811215
5     9811232
6     9811216
7     9811233
8     9811222
9     9811212
10    0000000
11    9892401
12    9811223
13    9811214
14    9811246
15    9811248
16    9811243
17    9811241
18    9811242
19    9811211
20    9811221
21    9811231
22    9811244
23    9811235
24    9811234
25    9892412
26    9892411
27    9811224
28    9811217
29    9811218
30    9811247
31    9811236
32    9811238
33    9811237
34    9811239
35    9811251
36    9811240
37    9811227
38    9811213
39    9811245
Name: post_id, dtype: object
0     0000000
1     9811518
2     9811521
3     9811504
4     9811524
5     9811532
6     9811514
7     9811502
8     9811505
9     9811515
10    9811523
11    9811525
12    9811517
13    9811534
14    9811522
15    9811503
16    9811526
17    9811516
18    9811513
19    9811531
20    9811511
21    9811533
22    9811501
23    9811512
Name: post_id, dtype: object
0     0000000
1     9850864
2     9850861
3     9850832
4     9850831
5     9850835
6     9850833
7     9850842
8     9850852
9     9850865
10    9850862
11    9850853
12    9850873
13    9850841
14    9850872
15    9850871
16    9850846
17    9850851
18    9850854
19    9850863
20    9850845
21    9850834
22    9850844
23    9850843
24    9850874
Name: post_id, dtype: object
0     0000000
1     9892431
2     9892474
3     9892478
4     9892435
5     9892463
6     9892443
7     9892442
8     9892471
9     9892423
10    9892472
11    9892455
12    9892420
13    9892422
14    9892445
15    9892447
16    9892473
17    9892433
18    9892427
19    9892465
20    9892476
21    9892421
22    9892426
23    9892453
24    9892452
25    9892459
26    9892458
27    9892441
28    9892428
29    9892432
30    9892425
31    9892451
32    9892461
33    9892446
34    9892424
35    9892477
36    9892457
37    9892436
38    9892437
39    9892434
40    9892448
41    9892444
42    9892456
43    9892464
44    9892454
45    9892429
46    9892462
47    9892475
Name: post_id, dtype: object
0      0000000
1      9894701
2      9894702
3      9894703
4      9860401
        ...
305    9870302
306    9870305
307    9870308
308    9870302
309    9870302
Name: post_id, Length: 310, dtype: object
0      0000000
1      9872372
2      9872369
3      9872336
4      9872343
        ...
413    9895501
414    9895502
415    9895503
416    9895505
417    9895508
Name: post_id, Length: 418, dtype: object
0     0000000
1     9810506
2     9810501
3     9810415
4     9810301
5     9810505
6     9810414
7     9810502
8     9810303
9     9810304
10    9810504
11    9810305
12    9810413
13    9810308
14    9810306
15    9810307
16    9810309
17    9810411
18    9810416
19    9810302
20    9810507
21    9810412
22    9810503
Name: post_id, dtype: object
0      0000000
1      9896463
2      9896405
3      9896435
4      9896447
        ...
253    9871306
254    9871301
255    9871304
256    9871305
257    9871302
Name: post_id, Length: 258, dtype: object
0     0000000
1     9813326
2     9813332
3     9813361
4     9813325
5     9813305
6     9813322
7     9813323
8     9813329
9     9813321
10    9813328
11    9813327
12    9813302
13    9813301
14    9813303
15    9813351
16    9813313
17    9813312
18    9813352
19    9813311
20    9813341
21    9813324
22    9813306
23    9813331
24    9813362
25    9813304
26    9813363
Name: post_id, dtype: object
0     0000000
1     0000000
2     9890921
3     9890921
4     9890921
5     9890841
6     9890842
7     9890916
8     9890914
9     9890915
10    9890911
11    9890912
12    9890913
13    9890831
14    9890851
15    9890701
16    9890843
Name: post_id, dtype: object
0      0000000
1      9890662
2      9890556
3      9890506
4      9890635
        ...
102    9890502
103    9890525
104    9890636
105    9890534
106    9890642
Name: post_id, Length: 107, dtype: object

0     0000000
1     9891203
2     9891237
3     9891205
4     9891204
5     9891261
6     9891201
7     9891263
8     9891267
9     9891258
10    9891249
11    9891224
12    9891233
13    9891207
14    9891214
15    9891216
16    9891264
17    9891274
18    9891234
19    9891246
20    9891245
21    9891213
22    9891266
23    9891255
24    9891202
25    9891256
26    9891248
27    9891231
28    9891215
29    9891206
30    9891222
31    9891253
32    9891242
33    9891217
34    9891273
35    9891244
36    9891257
37    9891254
38    9891251
39    9891247
40    9891271
41    9891223
42    9891236
43    9891225
44    9891211
45    9891259
46    9891241
47    9891221
48    9891243
49    9891232
50    9891272
51    9891235
52    9891252
53    9891212
Name: post_id, dtype: object
0     0000000
1     0000000
2     9891511
3     9891303
4     9891302
5     9891301
6     9891322
7     9891304
8     9891323
9     9891321
10    9891305
Name: post_id, dtype: object
0     0000000
1     9891745
2     9891762
3     9891742
4     9891611
5     9891623
6     9891608
7     9891764
8     9891613
9     9891756
10    9891758
11    9891753
12    9891752
13    9891754
14    9891751
15    9891755
16    9891757
17    9891741
18    9891612
19    9891765
20    9891622
21    9891761
22    0000000
23    9891606
24    9891607
25    9891601
26    9891602
27    9891604
28    9891603
29    9891605
30    9891763
31    9891621
32    9891744
33    9891746
34    9891743
Name: post_id, dtype: object
0     0000000
1     9890908
2     9891502
3     9891505
4     9891503
5     9891507
6     9891506
7     0000000
8     9890901
9     9890901
10    9890901
11    9890901
12    9890901
13    9890901
14    9890901
15    9891504
Name: post_id, dtype: object
0      0000000
1      9812114
2      9812133
3      9812173
4      9812122
        ...
215    9812121
216    9812144
217    9812117
218    9812117
219    9812132
Name: post_id, Length: 220, dtype: object
0     0000000
1     9892351
2     9892351
3     9892361
4     9892351
       ...
66    9892351
67    9892352
68    9892361
69    9892331
70    9892361
Name: post_id, Length: 71, dtype: object
0     0000000
1     9892203
2     9892206
3     9892205
4     9892111
5     9892202
6     9892208
7     9892207
8     9892112
9     9892201
10    9892204
Name: post_id, dtype: object
0     0000000
1     9810212
2     9810202
3     9810214
4     9810215
5     9810201
6     9810211
7     9810203
8     9810205
9     9810204
10    9810213
Name: post_id, dtype: object
0     0000000
1     9850824
2     9850805
3     9850821
4     9850822
5     9850811
6     9850804
7     9850823
8     9850803
9     9850812
10    9850813
11    9850801
12    9850802
Name: post_id, dtype: object
0     0000000
1     9810133
2     9810131
3     9810101
4     9810113
5     9810102
6     9810111
7     9810121
8     9810123
9     9810124
10    9810134
11    9810114
12    9810122
13    9810135
14    9810104
15    9810132
16    9810105
17    9810136
18    9810103
19    9810112
Name: post_id, dtype: object
0     0000000
1     9813404
2     9813401
3     9813406
4     9813403
5     9813402
6     9813405
7     9813407
8     9813623
9     9813271
10    9813414
11    9813411
12    9813415
13    9813417
14    9813418
15    9813412
16    9813413
17    9813416
18    9813629
19    9813419
20    9813408
21    9813624
22    9813622
23    9813628
24    9813621
25    9813631
26    9813627
27    9813632
28    9813626
29    9813625
30    9813409
Name: post_id, dtype: object
0     0000000
1     9813503
2     9813524
3     9813501
4     9813502
5     9813514
6     9813512
7     9813523
8     9813521
9     9813515
10    9813522
11    9813513
12    9813511
Name: post_id, dtype: object
0     0000000
1     9813601
2     9813602
3     9813605
4     9813603
5     9813607
6     9813606
7     9813604
8     9813609
9     9813611
10    9813612
11    9813608
Name: post_id, dtype: object
0     0000000
1     9814121
2     9814141
3     9814101
4     9814111
5     9814151
6     9814122
7     9814112
8     9814131
9     9814102
10    9814103
11    9814104
12    9814105
Name: post_id, dtype: object
0      0000000
1      9814264
2      9814375
3      9814275
4      9814323
        ...
112    9814265
113    9814411
114    9814403
115    9814221
116    9814309
Name: post_id, Length: 117, dtype: object
0     0000000
1     9870133
2     9870145
3     9870136
4     9870284
       ...
76    9870283
77    9870134
78    9870106
79    9870107
80    9870121
Name: post_id, Length: 81, dtype: object
0     0000000
1     9870015
2     9870056
3     9870004
4     9870045
5     9870038
6     9894204
7     9870022
8     9870032
9     9870065
10    9870005
11    9870069
12    9870057
13    9894205
14    9870034
15    9870063
16    9870064
17    9870033
18    9870036
19    9870011
20    9870058
21    9870059
22    9870014
23    9870035
24    9870061
25    9870053
26    9870051
27    9870055
28    9870043
29    9870068
30    9894209
31    9870037
32    9870052
33    9870006
34    9870013
35    9870012
36    9870067
37    9870031
38    9870054
39    9894207
40    9894208
41    9870024
42    9870025
43    9870024
44    9894206
45    9870044
46    9894203
47    9870021
48    9894202
49    9870001
50    9870002
51    9870066
52    9870062
53    9870003
54    9870026
55    9870041
56    9870042
57    9870046
58    9894201
Name: post_id, dtype: object
0     0000000
1     9862251
2     9862222
3     9862281
4     9862211
5     9862263
6     9862283
7     9862249
8     9862231
9     9862212
10    9862202
11    9862224
12    9862266
13    9862240
14    9862265
15    9862261
16    9862205
17    9862264
18    9862204
19    9862246
20    9862248
21    9862242
22    9862244
23    9862201
24    9862262
25    9862226
26    9862203
27    9862221
28    9862223
29    9862232
30    9862282
31    9862225
32    9862247
33    9862243
Name: post_id, dtype: object
0      0000000
1      9860782
2      9880453
3      9880471
4      9880426
        ...
103    9860761
104    9860743
105    9860742
106    9860704
107    9860781
Name: post_id, Length: 108, dtype: object
0      0000000
1      0100831
2      0100833
3      0100832
4      0100834
        ...
320    0101233
321    0100044
322    0101417
323    0101418
324    0101416
Name: post_id, Length: 325, dtype: object
0      0000000
1      0160865
2      0160835
3      0160115
4      0160179
        ...
195    0160825
196    0160841
197    0160838
198    0160145
199    0160823
Name: post_id, Length: 200, dtype: object
0      0000000
1      0130073
2      0130064
3      0130028
4      0130033
        ...
318    0130054
319    0130071
320    0130061
321    0130044
322    0130022
Name: post_id, Length: 323, dtype: object
0      0000000
1      0170806
2      0170831
3      0170854
4      0170816
        ...
136    0183506
137    0183502
138    0170838
139    0170021
140    0170885
Name: post_id, Length: 141, dtype: object
0     0000000
1     0100353
2     0100352
3     0100355
4     0100354
5     0100351
6     0100421
7     0100664
8     0100663
9     0100662
10    0100661
11    0100665
12    0100422
13    0100681
14    0100684
15    0100682
16    0100683
17    0100685
18    0100676
19    0100686
20    0100675
21    0100688
22    0100687
23    0100671
24    0100673
25    0100674
26    0100672
27    0100401
28    0100423
29    0100411
30    0100431
31    0100523
32    0100503
33    0100534
34    0100533
35    0100531
36    0100532
37    0100501
38    0100502
39    0100511
40    0100535
41    0100522
42    0100521
43    0100341
44    0100412
45    0100413
46    0100345
47    0100343
48    0100346
49    0100344
50    0100347
51    0100342
Name: post_id, dtype: object
0      0000000
1      0190402
2      0120024
3      0190321
4      0120855
        ...
104    0120823
105    0120823
106    0190204
107    0120036
108    0120869
Name: post_id, Length: 109, dtype: object
0     0000000
1     0185202
2     0185332
3     0185421
4     0185333
5     0185422
6     0185334
7     0185337
8     0185335
9     0185336
10    0185331
11    0185141
12    0185201
Name: post_id, dtype: object
0      0000000
1      0150023
2      0150836
3      0150079
4      0150071
        ...
233    0150333
234    0150087
235    0150324
236    0180725
237    0150815
Name: post_id, Length: 238, dtype: object

0     0000000
1     0181504
2     0181501
3     0181502
4     0181503
5     0181401
6     0181412
7     0181411
8     0181414
9     0181413
10    0181416
11    0181415
12    0181403
13    0181402
14    0100202
15    0000000
16    0100101
17    0100101
18    0100101
19    0100101
Name: post_id, dtype: object
0      0000000
1      0140013
2      0140067
3      0140004
4      0140112
        ...
227    0140111
228    0140102
229    0141411
230    0140016
231    0140033
Name: post_id, Length: 232, dtype: object
0     0000000
1     0183313
2     0184621
3     0184623
4     0184731
       ...
66    0183325
67    0184511
68    0184301
69    0183323
70    0183454
Name: post_id, Length: 71, dtype: object
0     0000000
1     0180431
2     0180411
3     0180322
4     0180412
       ...
87    0180402
88    0180321
89    0180432
90    0180403
91    0180401
Name: post_id, Length: 92, dtype: object
0     0000000
1     0140373
2     0140375
3     0140316
4     0140374
       ...
74    0140513
75    0140516
76    0140511
77    0140514
78    0140602
Name: post_id, Length: 79, dtype: object
0    0000000
1    0170204
2    0170203
3    0170201
4    0170202
5    0170205
6    0185511
Name: post_id, dtype: object
0    0000000
1    0184431
2    0184401
3    0184421
4    0184412
5    0184413
6    0184422
7    0184411
8    0184423
9    0184432
Name: post_id, dtype: object
0    0000000
1    0183203
2    0183205
3    0183202
4    0183201
5    0183204
Name: post_id, dtype: object
0     0000000
1     0182405
2     0182102
3     0182401
4     0182406
5     0182104
6     0182101
7     0182402
8     0182403
9     0182103
10    0182301
11    0182302
12    0182305
13    0182404
14    0182304
15    0182407
16    0182303
Name: post_id, dtype: object
0     0000000
1     0182637
2     0182643
3     0182622
4     0182615
       ...
70    0182509
71    0182512
72    0182503
73    0182501
74    0182502
Name: post_id, Length: 75, dtype: object
0     0000000
1     0181704
2     0181743
3     0181851
4     0181857
5     0181854
6     0181852
7     0181722
8     0181741
9     0181742
10    0181705
11    0181731
12    0181734
13    0181735
14    0181732
15    0181733
16    0181723
17    0181745
18    0181712
19    0181746
20    0181706
21    0181744
22    0181702
23    0181711
24    0181714
25    0181701
26    0181721
27    0181725
28    0181747
29    0181703
30    0181713
31    0181724
32    0181856
33    0181855
34    0181853
Name: post_id, dtype: object
0     0000000
1     0181621
2     0181617
3     0181602
4     0181616
5     0181627
6     0181615
7     0181611
8     0181613
9     0181618
10    0181605
11    0181625
12    0181603
13    0181628
14    0181623
15    0181635
16    0181624
17    0181629
18    0181614
19    0181633
20    0181632
21    0181634
22    0181604
23    0181631
24    0181622
25    0181612
26    0181626
27    0181601
28    0181606
Name: post_id, dtype: object
0     0000000
1     0181525
2     0181527
3     0181511
4     0181514
5     0181524
6     0181512
7     0181513
8     0181515
9     0181523
10    0181526
11    0181528
12    0181521
13    0181516
14    0181522
Name: post_id, dtype: object
0     0000000
1     0100451
2     0100452
3     0100453
4     0100441
5     0100443
6     0100454
7     0100445
8     0100455
9     0100442
10    0100456
11    0100444
Name: post_id, dtype: object
0     0000000
1     0191533
2     0191234
3     0191302
4     0191235
5     0191522
6     0191236
7     0191511
8     0191542
9     0191233
10    0191237
11    0191502
12    0191541
13    0191232
14    0191521
15    0191501
16    0191301
17    0191402
18    0191531
19    0191532
20    0191512
21    0191231
22    0191401
23    0191404
24    0191403
Name: post_id, dtype: object
0     0000000
1     0121124
2     0121136
3     0121121
4     0121101
5     0121132
6     0121123
7     0121122
8     0121353
9     0121242
10    0121243
11    0121113
12    0121135
13    0121111
14    0121351
15    0121102
16    0121126
17    0121116
18    0121134
19    0121241
20    0121115
21    0121133
22    0121352
23    0121131
24    0121137
25    0121114
26    0121125
27    0121103
28    0121106
29    0121104
30    0121105
31    0121112
Name: post_id, dtype: object
0    0000000
1    0190802
2    0190801
3    0190803
Name: post_id, dtype: object
0      0000000
1      9900055
2      9902435
3      9902324
4      9902222
        ...
281    9900071
282    9902373
283    9902495
284    9902453
285    9900064
Name: post_id, Length: 286, dtype: object
0      0000000
1      9920032
2      0000000
3      9921406
4      9920075
        ...
112    9920094
113    9920096
114    9920092
115    9920093
116    9920095
Name: post_id, Length: 117, dtype: object
0      0000000
1      9970832
2      9997205
3      9997312
4      9971205
        ...
282    9997643
283    9970037
284    9997121
285    9997683
286    9997684
Name: post_id, Length: 287, dtype: object
0      0000000
1      9980032
2      9996852
3      9998203
4      9980828
        ...
238    9980832
239    9980834
240    9980857
241    9980833
242    9980053
Name: post_id, Length: 243, dtype: object
0     0000000
1     9960078
2     9960086
3     9995103
4     9960001
5     9960084
6     9960026
7     9960023
8     9960074
9     9960071
10    9960002
11    9960032
12    9960082
13    9960073
14    9960033
15    9960034
16    9960077
17    9995101
18    9960076
19    9960031
20    9960022
21    9960079
22    9960024
23    9960052
24    9960035
25    0000000
26    9960021
27    9960061
28    9960041
29    9960081
30    9960054
31    9960087
32    9960083
33    9995102
34    9960028
35    9960011
36    9960088
37    9960053
38    9960085
39    9960027
40    9960111
41    9960051
42    9960072
43    9960112
44    9960075
45    9960025
Name: post_id, dtype: object
0     0000000
1     9910027
2     9910057
3     9910056
4     9910006
       ...
57    9910025
58    9910006
59    9900525
60    9910024
61    9910051
Name: post_id, Length: 62, dtype: object
0     0000000
1     9993222
2     9993164
3     9993106
4     9993235
       ...
72    9993154
73    9993134
74    9993156
75    9993133
76    9993162
Name: post_id, Length: 77, dtype: object
0     0000000
1     9950002
2     9950204
3     9950113
4     9950038
5     9950111
6     9950203
7     9950054
8     9950004
9     9950041
10    9950056
11    9950209
12    9950202
13    9950042
14    9950051
15    9950025
16    9950032
17    9950034
18    9950031
19    9950011
20    9950018
21    9950033
22    9950021
23    9950037
24    9950014
25    9950017
26    9950036
27    9950022
28    9950023
29    9950024
30    9950015
31    9950016
32    9950013
33    9950005
34    9950205
35    9950035
36    9950201
37    9950001
38    9950208
39    9950055
40    9950052
41    9950053
42    9950006
43    9950003
44    9950206
45    9950207
46    9950012
47    9950112
Name: post_id, dtype: object
0     0000000
1     9930022
2     9930006
3     9930072
4     9930031
5     9930033
6     9930034
7     9930083
8     9930005
9     9930021
10    9930032
11    9930062
12    9930064
13    9930063
14    9930041
15    9930014
16    9930085
17    9930051
18    9930084
19    9930054
20    9930023
21    9930071
22    9930052
23    9930004
24    9930016
25    9930013
26    9930011
27    9930061
28    9930086
29    9930035
30    9930024
31    9930053
32    9930075
33    9930017
34    9930003
35    9930012
36    9930042
37    9930082
38    9930001
39    9930081
40    9930074
41    9930007
42    9930073
43    9930002
44    9930087
45    9930015
Name: post_id, dtype: object
0     0000000
1     9940054
2     9940057
3     9940015
4     9940041
       ...
62    9940081
63    9940049
64    9940071
65    9940101
66    9940021
Name: post_id, Length: 67, dtype: object
0     0000000
1     9993722
2     9993747
3     9993749
4     9993744
       ...
73    9993772
74    9993706
75    9993705
76    9993718
77    9993709
Name: post_id, Length: 78, dtype: object
0     0000000
1     9994554
2     9994223
3     9994208
4     9994207
5     9994552
6     9994205
7     9994221
8     9994222
9     0000000
10    9994332
11    9994228
12    9994336
13    9994231
14    9994333
15    9994214
16    9994334
17    9994211
18    9994224
19    9994226
20    9994201
21    9994443
22    9994337
23    9994551
24    9994555
25    9994206
26    9994203
27    9994227
28    9994556
29    9994202
30    9994212
31    9994213
32    9994553
33    9994441
34    9994445
35    9994335
36    9994232
37    9994444
38    9994557
39    9994331
40    9994229
41    9994442
42    9994225
Name: post_id, dtype: object

0     0000000
1     9992211
2     9920473
3     9920474
4     9992224
5     9992252
6     9920582
7     9992212
8     9920471
9     9992201
10    9992261
11    9992204
12    9992221
13    9992203
14    9992241
15    9920581
16    9992256
17    9992244
18    9920583
19    9992205
20    9920476
21    9992255
22    9992251
23    9920478
24    9920584
25    9992234
26    9992254
27    9992264
28    9992242
29    9992222
30    9992266
31    9992243
32    9992231
33    9992265
34    9992263
35    9920475
36    9992267
37    9992213
38    9992223
39    9992232
40    9920472
41    9992253
42    9992202
43    9920477
44    9992262
45    9920479
46    9992233
Name: post_id, dtype: object
0     0000000
1     9900311
2     9900323
3     9900331
4     9900341
5     9900332
6     9900352
7     9900342
8     9900303
9     9900333
10    9900321
11    9900361
12    9900312
13    9900302
14    9900351
15    9900301
16    9900322
Name: post_id, dtype: object
0     0000000
1     9900411
2     9900402
3     9900408
4     9900405
5     9900409
6     9900403
7     9900407
8     9900401
9     9900404
10    9900406
Name: post_id, dtype: object
0     0000000
1     9993503
2     9993501
3     9993521
4     9993532
5     9993533
6     9993531
7     9993522
8     9993511
9     9993515
10    9993512
11    9993513
12    9993514
13    9993502
Name: post_id, dtype: object
0     0000000
1     9900714
2     9900743
3     9900721
4     9900702
5     9900734
6     9900732
7     9900731
8     9900733
9     9900741
10    9900713
11    9900712
12    9900735
13    9900703
14    9900742
15    9900701
16    9900711
Name: post_id, dtype: object
0     0000000
1     9901441
2     9901303
3     9901306
4     9901431
5     9901305
6     9901562
7     9901304
8     9901422
9     9901432
10    9901571
11    9901563
12    9901444
13    9901423
14    9901574
15    9901433
16    9901573
17    9901302
18    9901572
19    9901552
20    9901301
21    9901553
22    9901421
23    9901561
24    9901424
25    9901551
26    9901442
27    9901443
28    9901411
29    9901412
Name: post_id, dtype: object
0     0000000
1     0000000
2     9901122
3     9901131
4     9901152
5     9901153
6     9901276
7     9901141
8     9901273
9     9901142
10    9901275
11    9901113
12    9901112
13    9901111
14    9901133
15    9901144
16    9901145
17    9901271
18    9901132
19    9901134
20    9901114
21    9901146
22    9901272
23    9901143
24    9901161
25    9901121
26    9901154
27    9901151
28    9901164
29    9901163
30    9901165
31    9901162
32    9901274
Name: post_id, dtype: object
0     0000000
1     9994113
2     9994103
3     9994116
4     9994111
5     9994131
6     9994102
7     9994115
8     9994133
9     9994132
10    9994141
11    0000000
12    9994554
13    9994122
14    9994134
15    9994112
16    9994121
17    9994114
Name: post_id, dtype: object
0     0000000
1     9995401
2     9995414
3     9995405
4     9995402
5     9995404
6     9995413
7     9995412
8     9995411
9     9995415
10    9995403
11    9995406
Name: post_id, dtype: object
0     0000000
1     9996211
2     9996103
3     9996106
4     9996212
5     9996211
6     9996215
7     9996105
8     9996102
9     9996213
10    9996104
11    9996107
12    9996101
13    9996214
Name: post_id, dtype: object
0    0000000
1    9994602
2    9994603
3    9994605
4    9994601
5    9994604
Name: post_id, dtype: object
0     0000000
1     9995312
2     9995313
3     9995521
4     9995603
5     9995604
6     0000000
7     9995601
8     9995601
9     9995314
10    9995522
11    9995602
12    9995311
Name: post_id, dtype: object
0     0000000
1     9960211
2     9960213
3     9960212
4     0000000
5     9960301
6     9960301
7     9960301
8     9960301
9     9960301
10    9960301
11    9960301
12    9960301
13    9960301
Name: post_id, dtype: object
0    0000000
1    9995208
2    9995203
3    9995201
4    9995202
5    9995205
6    9995207
7    9995206
8    9995204
Name: post_id, dtype: object
0    0000000
1    9996312
2    9996402
3    9996315
4    9996403
5    9996311
6    9996313
7    0000000
8    9996801
9    9996314
Name: post_id, dtype: object
0     0000000
1     9920332
2     9920302
3     9992171
4     9920315
5     9920334
6     9920324
7     9992177
8     9920333
9     9920311
10    9992178
11    9920261
12    9920321
13    9920335
14    9920313
15    9920312
16    9920265
17    9920331
18    9920314
19    9920263
20    9992179
21    9920351
22    9920342
23    9920323
24    9920341
25    9920352
26    9920322
27    9992172
28    9920301
29    9992176
30    9920343
31    9920264
32    9920344
33    9992174
34    9992175
35    9920325
36    9920262
37    9992173
Name: post_id, dtype: object
0     0000000
1     9920602
2     9990151
3     9990213
4     9990152
5     9990121
6     9990131
7     9990132
8     9990133
9     9990145
10    9990134
11    9990212
12    9990211
13    9990141
14    9990361
15    9990144
16    9990122
17    9920601
18    9990143
19    9920603
20    9990153
21    9990142
22    9990214
Name: post_id, dtype: object
0     0000000
1     9991356
2     9991323
3     9991507
4     9991504
       ...
72    9991362
73    9991343
74    9991431
75    9991346
76    9991303
Name: post_id, Length: 77, dtype: object
0     0000000
1     9920852
2     9920771
3     9920831
4     9920832
5     9920861
6     9920775
7     9920841
8     9920864
9     9920862
10    9920821
11    9920863
12    9920778
13    9920773
14    9920812
15    9920777
16    9920802
17    9920811
18    9920801
19    9920851
20    9920779
21    9920776
22    9920774
23    9920772
Name: post_id, dtype: object
0     0000000
1     9990436
2     9990425
3     9990427
4     9990426
5     9990424
6     9990433
7     9990434
8     9990603
9     9991113
10    9990421
11    9990431
12    9990432
13    9990423
14    9990605
15    9990435
16    9991112
17    9990604
18    9991111
19    9990601
20    9990602
21    9990422
22    9990606
Name: post_id, dtype: object
0     0000000
1     9971311
2     9971316
3     9971321
4     9971313
5     9971336
6     9971315
7     9971337
8     9971331
9     9971312
10    9971334
11    9971332
12    9971322
13    9971317
14    9971314
15    9971335
16    9971333
17    9971338
18    9971339
19    9971301
Name: post_id, dtype: object
0     0000000
1     9997724
2     9997701
3     9997781
4     9997714
       ...
57    9997756
58    9997744
59    9997753
60    9997749
61    9997723
Name: post_id, Length: 62, dtype: object
0     0000000
1     9998436
2     9998433
3     9998315
4     9998311
5     9998312
6     9998314
7     9998522
8     9998317
9     9998435
10    9998304
11    0000000
12    9998431
13    9998313
14    9998525
15    9998523
16    9998524
17    9998316
18    9998303
19    9998438
20    9998521
21    9998437
22    9998434
23    9998432
24    9998301
25    9998302
Name: post_id, dtype: object
0      0000000
1      9608113
2      9602156
3      9602102
4      9608042
        ...
177    9608115
178    9601105
179    9608165
180    9608044
181    9608141
Name: post_id, Length: 182, dtype: object
0      0000000
1      9650031
2      9650032
3      9650012
4      9650007
        ...
226    9650863
227    9650821
228    9650046
229    9650875
230    9650811
Name: post_id, Length: 231, dtype: object
0      0000000
1      9638006
2      9630667
3      9630107
4      9630117
        ...
236    9638841
237    9638832
238    9630665
239    9638803
240    9638011
Name: post_id, Length: 241, dtype: object
0      0000000
1      9748212
2      9748213
3      9708017
4      9718172
        ...
260    9728334
261    9728337
262    9728332
263    9728333
264    9728335
Name: post_id, Length: 265, dtype: object
0      0000000
1      9610075
2      9610901
3      9610912
4      9610942
        ...
220    9610961
221    9610078
222    9610871
223    9610066
224    9610092
Name: post_id, Length: 225, dtype: object
0      0000000
1      9620811
2      9620816
3      9620834
4      9620868
        ...
150    9620059
151    9620862
152    9620825
153    9620813
154    9620818
Name: post_id, Length: 155, dtype: object
0      0000000
1      9660819
2      9660818
3      9660817
4      9660091
        ...
279    9694109
280    9660071
281    9660052
282    9660083
283    9660824
Name: post_id, Length: 284, dtype: object

0     0000000
1     9792521
2     9760152
3     9760006
4     9792501
5     9792541
6     9760025
7     9760007
8     9760001
9     9760032
10    9760016
11    9760053
12    9760022
13    9760034
14    9792511
15    9760014
16    9760012
17    9760052
18    9760013
19    9760005
20    9760002
21    9792531
22    9760154
23    9760004
24    9760003
25    9760015
26    9792533
27    9760031
28    9792532
29    9760037
30    9760042
31    9792542
32    9760033
33    9760011
34    9760041
35    9792522
36    9760051
37    9760036
38    9760021
39    9760153
40    9760035
41    9760026
42    9760024
43    9760151
44    9792512
45    9760023
Name: post_id, dtype: object
0      0000000
1      9640982
2      9640929
3      9640938
4      9640802
        ...
248    9691401
249    9640971
250    9691402
251    9640928
252    9640906
Name: post_id, Length: 253, dtype: object
0     0000000
1     9634111
2     9634115
3     9634112
4     9634114
5     9634113
6     9633602
7     9633601
8     9633603
9     9634604
10    9634605
11    9634614
12    9634613
13    9634602
14    9634603
15    9634606
16    9634611
17    9634601
18    9634612
19    9634316
20    9634322
21    9634431
22    9634313
23    9634311
24    9634435
25    9634203
26    9634434
27    9634323
28    9634541
29    9634545
30    9634433
31    9634202
32    9634318
33    9634321
34    9634317
35    9634205
36    9634432
37    9634201
38    9634543
39    9634324
40    9634436
41    9634315
42    9634312
43    9634204
44    9634544
45    9634314
46    9634542
47    9634702
48    9634701
Name: post_id, dtype: object
0      0000000
1      9792133
2      9792144
3      9792145
4      9792155
        ...
132    9750012
133    9750007
134    9750048
135    9750008
136    9750057
Name: post_id, Length: 137, dtype: object
0      0000000
1      0520015
2      0520025
3      0520002
4      0590151
        ...
300    9600808
301    9600805
302    9600806
303    9600802
304    9600486
Name: post_id, Length: 305, dtype: object
0     0000000
1     9691107
2     9691104
3     9691201
4     9691106
       ...
90    9691119
91    9691143
92    9691129
93    9691145
94    9691205
Name: post_id, Length: 95, dtype: object
0     0000000
1     9691633
2     9691633
3     9691603
4     9691623
5     9691634
6     9691661
7     9691619
8     9691642
9     9691601
10    9691635
11    9691618
12    9691613
13    9691633
14    9691615
15    9691608
16    9691662
17    9691631
18    9691628
19    9691617
20    9691625
21    9691624
22    9691634
23    9691634
24    9691627
25    9691605
26    9691604
27    9691632
28    9691616
29    9691663
30    9691626
31    9691621
32    9691652
33    9691612
34    9691607
35    9691629
36    9691611
37    9691606
38    9691635
39    9691654
40    9691602
41    9691653
42    9691651
43    9691641
44    9691622
45    9691614
46    9691643
47    9691631
Name: post_id, dtype: object
0     0000000
1     9691701
2     9691782
3     9691785
4     9691781
5     9691713
6     9691711
7     9691721
8     9691712
9     9691784
10    9691788
11    9691786
12    9691780
13    9691787
14    9691789
15    9691714
16    9691751
17    9691741
18    9691783
19    9691722
20    9691761
21    9691731
22    9691771
Name: post_id, dtype: object
0     0000000
1     9601465
2     9601409
3     9601401
4     9601423
       ...
66    9601466
67    9601461
68    9601451
69    9601482
70    9601501
Name: post_id, Length: 71, dtype: object
0    0000000
1    9691301
2    0000000
3    9640091
Name: post_id, dtype: object
0     0000000
1     9690404
2     9690402
3     9690401
4     9690401
5     9690402
6     9690404
7     9690401
8     9690404
9     9690401
10    9690401
11    9690404
12    9690404
13    9690401
14    9690401
15    9690403
16    9690401
17    9690402
18    9690402
19    9690403
20    9690403
21    9690403
22    9690401
23    9690401
24    9690403
25    9690401
26    9690403
27    9690402
28    9690402
29    9690401
30    9690404
31    9690403
32    9690404
33    9690404
34    9690401
35    9690404
36    9690402
37    9690402
38    9690402
39    9690401
40    9690404
41    9690401
42    9690402
43    9690404
44    9690401
45    9690401
46    9690404
47    9690401
48    9690404
49    9690401
50    9690404
51    9690401
Name: post_id, dtype: object
0     0000000
1     9620512
2     9620504
3     9620516
4     9620513
5     9620514
6     9620502
7     9620503
8     9620511
9     9620515
10    9620622
11    9620623
12    9620501
13    9620621
Name: post_id, dtype: object
0     0000000
1     9695333
2     9695315
3     9695331
4     9695316
5     9695318
6     9695326
7     9695202
8     9695207
9     9695205
10    9695334
11    9695343
12    9695342
13    9695208
14    9695323
15    9695321
16    9695344
17    9695345
18    9695317
19    9695203
20    9695201
21    9695312
22    9695311
23    9695332
24    9695325
25    9695335
26    9695341
27    9695313
28    9695314
29    9695204
30    9695324
31    9695206
32    9695322
Name: post_id, dtype: object
0     0000000
1     9670521
2     9670524
3     9670532
4     9670522
5     9670523
6     9670525
7     9670526
8     9670531
9     9670527
10    9670528
Name: post_id, dtype: object
0     0000000
1     9680443
2     9680422
3     9680602
4     9680434
5     9680415
6     9680445
7     9680414
8     9680444
9     9680432
10    9680441
11    9680601
12    9680606
13    9680411
14    9680604
15    9680412
16    9680423
17    9680421
18    9680442
19    9680431
20    9680605
21    9680433
22    9680607
23    9680603
24    9680413
Name: post_id, dtype: object
0     0000000
1     9670507
2     9670605
3     9670341
4     9670321
       ...
73    9670318
74    9670314
75    9670611
76    9670333
77    9670336
Name: post_id, Length: 78, dtype: object
0     0000000
1     9660402
2     9660404
3     9660405
4     9660403
5     0000000
6     9660501
7     9660501
8     9660501
9     9660501
10    9660501
11    9660501
12    9660501
13    9660501
14    9660501
15    9660501
16    9660501
17    9660501
18    9660501
19    9660501
20    9660501
21    9660501
22    9660401
23    9660401
24    9660401
25    9660401
26    9660401
27    9660401
28    9660401
29    9692701
30    9692701
31    9692701
32    9692701
33    9692701
34    9692701
35    9692701
36    9692701
37    9692701
38    9692701
39    9692701
40    9692701
41    9692701
42    9692701
43    9692701
Name: post_id, dtype: object
0     0000000
1     9694734
2     9694732
3     9694731
4     9694733
5     9694737
6     9694735
7     9694736
8     9694402
9     9694512
10    9694405
11    9694515
12    9694622
13    9694623
14    9694621
15    9694624
16    9694403
17    9694401
18    9694406
19    9694514
20    9694513
21    9694404
22    9694511
Name: post_id, dtype: object
0    0000000
1    9693303
2    9693304
3    9693302
4    9693301
Name: post_id, dtype: object
0      0000000
1      9693121
2      9693122
3      9693101
4      9693111
        ...
132    9693121
133    9693121
134    9693141
135    9692751
136    9693288
Name: post_id, Length: 137, dtype: object
0     0000000
1     9696517
2     9696511
3     9696518
4     9696535
       ...
81    9696519
82    9696532
83    9696506
84    9696522
85    9696504
Name: post_id, Length: 86, dtype: object
0     0000000
1     9693543
2     9693554
3     9693545
4     9693555
5     9693544
6     9693556
7     9693553
8     9693551
9     9693541
10    9693552
11    9693546
12    9693542
Name: post_id, dtype: object
0     0000000
1     9697206
2     9697204
3     9697323
4     9697325
5     9697202
6     9697324
7     9697203
8     9697312
9     9697322
10    9697205
11    9697313
12    9697207
13    9697321
14    9697326
15    9697208
16    9697209
17    9697314
18    9697201
19    9697311
20    9697315
Name: post_id, dtype: object
0     0000000
1     9697518
2     9697407
3     9697517
4     9697516
5     9697515
6     9697512
7     9697403
8     9697404
9     9697405
10    9697514
11    9697402
12    9697401
13    9697406
14    0000000
15    9697413
16    9697519
17    9697511
Name: post_id, dtype: object
0     0000000
1     9680002
2     9680005
3     9680326
4     9680011
5     9680012
6     9680321
7     9680325
8     9680324
9     9680014
10    9680004
11    9680006
12    9680015
13    9680003
14    9680013
15    9680016
16    9680001
17    9680323
18    9680322
Name: post_id, dtype: object

0    0000000
1    9680214
2    9680211
3    9680212
4    9680104
5    9680215
6    9680103
7    9680102
8    9680101
9    9680213
Name: post_id, dtype: object
0      0000000
1      9696272
2      9696222
3      9696226
4      9696221
        ...
258    9696241
259    9696405
260    9696266
261    9696265
262    9696401
Name: post_id, Length: 263, dtype: object
0     0000000
1     9618043
2     9618044
3     9618047
4     9618061
5     9618011
6     9618091
7     9618051
8     9618056
9     9618081
10    9618052
11    9618055
12    9618041
13    9618042
14    9618021
15    9618001
16    9618053
17    9618054
18    9618071
19    9618046
20    9618045
21    9618031
Name: post_id, dtype: object
0    0000000
1    9690101
2    9690104
3    9690103
4    0000000
5    9690106
6    9690105
Name: post_id, dtype: object
0    0000000
1    9610105
2    9610103
3    9610102
4    9610106
5    9610101
6    9610104
Name: post_id, dtype: object
0     0000000
1     9690206
2     9690272
3     9690236
4     9690287
       ...
83    9690213
84    9690261
85    9690244
86    9690236
87    9690286
Name: post_id, Length: 88, dtype: object
0     0000000
1     9636113
2     9636111
3     9636147
4     9636114
5     9636145
6     9635662
7     9636106
8     9635681
9     9635685
10    9636105
11    9636152
12    9636144
13    9636103
14    9635682
15    9635683
16    9636153
17    9636123
18    9636131
19    9636112
20    9635664
21    9636101
22    9635671
23    9636102
24    9636146
25    9636141
26    9635684
27    9635663
28    9636122
29    9636121
30    9636104
31    9636115
32    9636143
33    9636151
34    9635672
35    9636142
36    9635661
Name: post_id, dtype: object
0     0000000
1     9635322
2     9635114
3     9635119
4     9635111
5     9635115
6     9635116
7     9635202
8     9635113
9     9635321
10    9635203
11    9635201
12    9635118
13    9635112
14    9635323
15    9635117
Name: post_id, dtype: object
0     0000000
1     9635342
2     9635537
3     9635343
4     9635532
5     9635522
6     9635411
7     9635406
8     9635536
9     9635534
10    9635341
11    9635404
12    9635531
13    9635539
14    9635402
15    9635403
16    9635538
17    9635521
18    9635407
19    9635405
20    9635401
21    9635408
22    9635344
23    9635535
24    9635533
Name: post_id, dtype: object
0    0000000
1    9638404
2    9638401
3    9638403
4    9638407
5    9638402
6    9638406
7    9638408
8    0000000
Name: post_id, dtype: object
0     0000000
1     9637826
2     9637864
3     0000000
4     9637833
       ...
64    9637861
65    9637814
66    9637801
67    9637886
68    9637863
Name: post_id, Length: 69, dtype: object
0     0000000
1     9636312
2     9636313
3     9636311
4     9636304
5     9636316
6     9636315
7     9636314
8     9636302
9     9636305
10    9636306
11    9636303
12    9636301
Name: post_id, dtype: object
0     0000000
1     9638114
2     9638202
3     9638112
4     9638203
5     9638113
6     9638206
7     9638207
8     9638204
9     9638115
10    9638205
11    9638116
12    9638111
13    9638201
Name: post_id, dtype: object
0     0000000
1     9636204
2     9636214
3     9636206
4     9636207
5     9636202
6     9636216
7     9636208
8     9636205
9     9636213
10    9636215
11    9636211
12    9636218
13    9636201
14    9636212
15    9636217
16    9636203
Name: post_id, dtype: object
0    0000000
1    9638303
2    9638307
3    9638308
4    9638305
5    9638306
6    9638304
7    9638302
8    9638301
Name: post_id, dtype: object
0     0000000
1     9637702
2     9637753
3     9637745
4     9637765
       ...
86    9637754
87    9637718
88    9637712
89    9637752
90    9637784
Name: post_id, Length: 91, dtype: object
0     0000000
1     9633521
2     9633524
3     9633522
4     9633403
5     9633401
6     9633523
7     9633316
8     9633405
9     9633406
10    9633314
11    9633404
12    9633312
13    9633313
14    9633402
15    9633311
16    9633525
17    9633315
Name: post_id, dtype: object
0    0000000
1    9790404
2    9790406
3    9790401
4    9790407
5    9790403
6    9790402
7    9790408
8    9790405
Name: post_id, dtype: object
0     0000000
1     9790603
2     9790605
3     9790515
4     9790606
5     9790604
6     9790514
7     9790602
8     9790601
9     9790511
10    9790513
11    9790512
Name: post_id, dtype: object
0     0000000
1     9791171
2     9791101
3     9791131
4     9791141
5     0000000
6     9791111
7     9791162
8     9791132
9     9791112
10    9791121
11    9791151
12    9791152
13    9791161
Name: post_id, dtype: object
0    0000000
1    9791201
2    9791202
Name: post_id, dtype: object
0    0000000
1    9791306
2    9791301
3    9791304
4    9791305
5    9791303
6    9791302
7    9791308
8    9791307
Name: post_id, dtype: object
0     0000000
1     9791433
2     9791442
3     9791463
4     9791411
5     9791451
6     9791441
7     9791472
8     9791453
9     9791462
10    9791401
11    9791402
12    9791471
13    9791412
14    9791421
15    9791452
16    9791432
17    9791422
18    9791423
19    9791461
20    9791431
Name: post_id, dtype: object
0     0000000
1     9791751
2     9791535
3     9791522
4     9791526
5     9791544
6     9791543
7     9791545
8     9791536
9     9791505
10    9791531
11    9791753
12    9791512
13    9791513
14    9791521
15    9791533
16    9791504
17    9791756
18    9791542
19    9791525
20    9791541
21    9791501
22    9791511
23    9791757
24    9791523
25    9791503
26    9791755
27    9791752
28    9791532
29    9791502
30    9791754
31    0000000
32    9791524
33    9791534
Name: post_id, dtype: object
0    0000000
1    9791602
2    9791601
3    9791604
4    9791603
Name: post_id, dtype: object
0     0000000
1     9792705
2     9792709
3     9792704
4     9792703
5     9792611
6     9792706
7     9792711
8     9792708
9     9792707
10    9792702
11    9792701
Name: post_id, dtype: object
0     0000000
1     9601812
2     9601721
3     9601803
4     9601633
5     9601814
6     9601801
7     9601811
8     9601815
9     9601635
10    9601804
11    9601632
12    9601723
13    9601634
14    9601722
15    9601802
16    9601636
17    9601631
18    9601813
19    9601724
Name: post_id, dtype: object
0      0000000
1      3100004
2      3190314
3      3114141
4      3111122
        ...
142    3100847
143    3111135
144    3100013
145    3100014
146    3100902
Name: post_id, Length: 147, dtype: object
0     0000000
1     3170075
2     3191415
3     3170074
4     3160036
       ...
69    3170055
70    3170054
71    3191235
72    3160025
73    3170063
Name: post_id, Length: 74, dtype: object
0      0000000
1      3000818
2      3000873
3      3000871
4      3000874
        ...
114    3000003
115    3004112
116    3000801
117    3000036
118    3000063
Name: post_id, Length: 119, dtype: object
0     0000000
1     3060012
2     3060044
3     3060224
4     3060225
       ...
83    3060113
84    3060203
85    3060114
86    3060022
87    3060004
Name: post_id, Length: 88, dtype: object
0     0000000
1     3150148
2     3150038
3     3150021
4     3150030
       ...
89    3150142
90    3150156
91    3150167
92    3150018
93    3150017
Name: post_id, Length: 94, dtype: object
0     0000000
1     3070028
2     3070045
3     3070041
4     3070042
5     3070031
6     3070055
7     3070002
8     3070007
9     3070027
10    3070015
11    3070021
12    3070005
13    3070012
14    3070051
15    3070006
16    3070011
17    3070008
18    3070023
19    3070038
20    3070054
21    3070034
22    3070016
23    3070053
24    3070029
25    3070035
26    3070043
27    3070044
28    3070052
29    3070013
30    3070026
31    3070025
32    3070014
33    3070037
34    3070003
35    3070032
36    3070036
37    3070024
38    3070004
39    3070022
40    3070033
41    3070001
42    3070046
43    3070017
44    3070018
Name: post_id, dtype: object
0     0000000
1     3010821
2     3010838
3     3010857
4     3010801
       ...
72    3010811
73    3010842
74    3010831
75    3010011
76    3010041
Name: post_id, Length: 77, dtype: object
0     0000000
1     3040074
2     3040803
3     3040057
4     3040053
       ...
75    3040044
76    3040043
77    3040045
78    3040035
79    3040012
Name: post_id, Length: 80, dtype: object

0     0000000
1     3030002
2     3030011
3     3030016
4     3002525
       ...
77    3002707
78    3002711
79    3002715
80    3002522
81    3002701
Name: post_id, Length: 82, dtype: object
0      0000000
1      3130102
2      3130121
3      3130132
4      3130007
        ...
100    3130006
101    3130043
102    3130013
103    3130214
104    3130223
Name: post_id, Length: 105, dtype: object
0     0000000
1     3180001
2     3180024
3     3180021
4     3180012
5     3180022
6     3180103
7     3180031
8     3180105
9     3180004
10    3180023
11    3180106
12    3180003
13    3180002
14    3180034
15    3180013
16    3180104
17    3180014
18    3180011
19    3180025
20    3180005
21    3180033
22    3180032
23    3180101
24    3180102
Name: post_id, dtype: object
0     0000000
1     3191541
2     3191547
3     3191546
4     3191544
5     3191545
6     3191543
7     3191542
8     3191702
9     3191703
10    3191704
11    3191714
12    3191715
13    3191712
14    3191711
15    3191713
16    3191727
17    3191726
18    3191721
19    3191723
20    3191724
21    3191722
22    3191725
23    3191552
24    3191554
25    3191558
26    3191555
27    3191559
28    3191553
29    3191551
30    3191556
31    3191557
32    3191538
33    3191535
34    3191532
35    3191533
36    3191534
37    3191537
38    3191536
39    3191531
40    3191701
Name: post_id, dtype: object
0     0000000
1     3091616
2     3190206
3     3091717
4     3091632
       ...
59    3091633
60    3091736
61    3091723
62    3091715
63    3190203
Name: post_id, Length: 64, dtype: object
0     0000000
1     3020006
2     3020037
3     3020026
4     3020011
       ...
60    3001532
61    3020039
62    3020007
63    3001538
64    3001545
Name: post_id, Length: 65, dtype: object
0     0000000
1     3001282
2     3001221
3     3001204
4     3001283
5     3001286
6     3001214
7     3001211
8     3001281
9     3001213
10    3001232
11    3001216
12    3001235
13    3001288
14    3001212
15    3001233
16    3001217
17    3001231
18    3001284
19    3001203
20    3001285
21    3001223
22    3001224
23    3001225
24    3001237
25    3001236
26    3001234
27    3001215
28    3001202
29    3001205
30    3001201
31    3001206
32    3001207
33    3001287
34    3001222
Name: post_id, dtype: object
0      0000000
1      3050062
2      3004203
3      0000000
4      3004205
        ...
242    3001258
243    3001248
244    3001249
245    3003252
246    3004247
Name: post_id, Length: 247, dtype: object
0      0000000
1      3120056
2      3111241
3      3111264
4      3111201
        ...
96     3111232
97     3111231
98     3111251
99     3111224
100    3111214
Name: post_id, Length: 101, dtype: object
0     0000000
1     3140021
2     3112211
3     3140002
4     3140017
5     3112204
6     3140015
7     3140036
8     3140004
9     3112215
10    3140037
11    3140028
12    3140026
13    3140031
14    3140016
15    3140030
16    3112221
17    3140003
18    3112222
19    3140027
20    3140044
21    3112207
22    3140001
23    3140025
24    3140038
25    3140007
26    3140013
27    3140047
28    3112201
29    3140005
30    3112206
31    3112202
32    3112214
33    3140042
34    3140043
35    3140048
36    3112205
37    3112212
38    3140046
39    3112213
40    3140022
41    3112224
42    3140041
43    3140035
44    3140034
45    3140033
46    3112203
47    3112223
48    3140014
49    3140012
50    3140039
51    3140011
52    3140032
53    3140006
54    3140045
55    3140023
56    3140024
Name: post_id, dtype: object
0     0000000
1     3112425
2     3112424
3     3112436
4     3112435
5     3112402
6     3112401
7     3112422
8     3112426
9     3112441
10    3112403
11    3112440
12    3112431
13    3112442
14    3112444
15    3112407
16    3112434
17    3112406
18    3112443
19    3112448
20    3112446
21    3112408
22    3112405
23    3112421
24    3112418
25    3112437
26    3112415
27    3112409
28    3112410
29    3112423
30    3112419
31    3112449
32    3112433
33    3112416
34    3112447
35    3112445
36    3112404
37    3112412
38    3112432
39    3112417
Name: post_id, dtype: object
0     0000000
1     3020111
2     3020101
3     3020116
4     3020107
5     3020103
6     3020123
7     3020104
8     3020128
9     3020125
10    3020119
11    3020122
12    3020126
13    3020118
14    3020115
15    3020112
16    3020117
17    3020131
18    3020109
19    3020127
20    3020108
21    3020132
22    3020102
23    3020121
24    3020124
25    3020106
26    3020105
27    3020110
Name: post_id, dtype: object
0     0000000
1     3114611
2     3192135
3     3192144
4     3192415
       ...
78    3193103
79    3192266
80    3192417
81    3192414
82    3192222
Name: post_id, Length: 83, dtype: object
0     0000000
1     3110134
2     3192102
3     3110125
4     3110135
5     3110136
6     3110116
7     3110123
8     3110131
9     3110133
10    3110111
11    3192105
12    3192106
13    3110126
14    3192107
15    3110105
16    3110106
17    3110110
18    3110124
19    3110112
20    3110104
21    3110122
22    3110121
23    3110117
24    3192103
25    3110113
26    3110115
27    3110108
28    3110109
29    3110107
30    3110114
31    3192104
32    3110118
33    3110132
34    3110102
35    3110101
36    3110103
Name: post_id, dtype: object
0      0000000
1      3004523
2      3080836
3      3004516
4      3004512
        ...
163    3091116
164    3004542
165    3080838
166    3091102
167    3080824
Name: post_id, Length: 168, dtype: object
0     0000000
1     3060631
2     3060514
3     3060504
4     3060503
5     3060615
6     3060613
7     3060622
8     3060601
9     3060621
10    3060626
11    3060617
12    3060611
13    3060654
14    3060657
15    3060603
16    3060643
17    3060636
18    3060641
19    3060515
20    3060513
21    3060635
22    3060608
23    3060606
24    3060604
25    3060644
26    3060653
27    3060501
28    3060512
29    3060633
30    3060614
31    3060505
32    3060656
33    3060652
34    3060634
35    3060645
36    3060642
37    3060616
38    3060612
39    3060651
40    3060602
41    3060632
42    3060623
43    3060511
44    3060605
45    3060637
46    3060658
47    3060655
48    3060625
49    3060624
50    3060502
51    3060607
Name: post_id, dtype: object
0     0000000
1     3000621
2     3000602
3     3000626
4     3000727
       ...
89    3000724
90    3000747
91    3000742
92    3000735
93    3000606
Name: post_id, Length: 94, dtype: object
0     0000000
1     3000212
2     3150078
3     3000205
4     3150063
5     3150071
6     3150054
7     3150053
8     3150055
9     3000203
10    3000213
11    3150064
12    3000124
13    3000132
14    3000201
15    3150056
16    3000127
17    3000123
18    3150065
19    3150076
20    3150057
21    3000135
22    3150061
23    3000214
24    3000121
25    3000211
26    3150052
27    3000131
28    3000204
29    3150067
30    3150074
31    3150058
32    3150077
33    3000202
34    3000136
35    3150066
36    3150075
37    3000133
38    3150051
39    3000122
40    3150073
41    3150072
42    3000134
43    3000125
44    3000126
45    3150068
46    3150069
47    3150062
Name: post_id, dtype: object
0     0000000
1     3091241
2     3091456
3     3091216
4     3091234
       ...
77    3091342
78    3091455
79    3091344
80    3091231
81    3091333
Name: post_id, Length: 82, dtype: object
0     0000000
1     3140133
2     0000000
3     3140124
4     3140254
5     3140257
6     3140144
7     3140128
8     3140116
9     3140134
10    3140143
11    3140127
12    3140101
13    3140115
14    3140112
15    3140123
16    3140131
17    3140253
18    3140255
19    3140125
20    3140126
21    3140132
22    3140342
23    3140347
24    3140346
25    3140344
26    3140343
27    3140345
28    3140102
29    3140114
30    3140122
31    3140408
32    3140407
33    3140103
34    3140051
35    3140146
36    3140145
37    3140145
38    3140148
39    3140142
40    3140135
41    3140121
42    3140111
43    3140341
44    3140252
45    3140258
46    3140113
47    3140256
48    3140147
Name: post_id, dtype: object
0     0000000
1     3113831
2     3113832
3     3113814
4     3113518
5     3113803
6     3113827
7     3113817
8     3113515
9     3113516
10    3113824
11    3111705
12    3113822
13    3113508
14    3113802
15    3113804
16    3111724
17    3111715
18    3111716
19    3113821
20    3113807
21    3113816
22    3113813
23    3113514
24    3113835
25    3113823
26    3113811
27    3113815
28    3113812
29    3113501
30    3113511
31    3113512
32    3113513
33    3113833
34    3111713
35    3111701
36    3111722
37    3113801
38    3111703
39    3113825
40    3113503
41    3113805
42    3113507
43    3113505
44    3111712
45    3113517
46    3113806
47    3113834
48    3113836
49    3111714
50    3111702
51    3113506
52    3113504
53    3113826
54    3111704
55    3111723
56    3111711
57    3111721
58    3113502
Name: post_id, dtype: object

0     0000000
1     3111535
2     3112101
3     3111506
4     3112118
       ...
57    3111401
58    3111537
59    3111426
60    3111514
61    3111425
Name: post_id, Length: 62, dtype: object
0     0000000
1     3002346
2     3002348
3     3002315
4     3002354
       ...
78    3002426
79    3002343
80    3002337
81    3002357
82    3002358
Name: post_id, Length: 83, dtype: object
0     0000000
1     3113404
2     3190122
3     3190137
4     3190126
5     3113423
6     3190125
7     3190106
8     3113405
9     3113436
10    3190115
11    3113403
12    3113412
13    3113431
14    3113417
15    3113434
16    3190107
17    3113425
18    3190102
19    3113402
20    3190104
21    3190103
22    3113432
23    3113426
24    3113406
25    3113401
26    3113433
27    3190135
28    3113435
29    3190113
30    3190112
31    3190114
32    3190105
33    3190136
34    3190131
35    3113414
36    3190116
37    3113422
38    3190111
39    3190134
40    3113411
41    3190121
42    3190101
43    3113424
44    3190123
45    3190124
46    3190133
47    3113437
48    3113415
49    3190132
50    3190108
51    3113421
52    3113413
53    3113416
Name: post_id, dtype: object
0     0000000
1     3113137
2     3113147
3     3113152
4     3113111
5     3113135
6     3113114
7     3113156
8     3113131
9     3113157
10    3113145
11    3113153
12    3113122
13    3113134
14    3113141
15    3113151
16    3113146
17    3113107
18    3113132
19    3113104
20    3113106
21    3113113
22    3113117
23    3113144
24    3113154
25    3113125
26    3113155
27    3113138
28    3113105
29    3113108
30    3113112
31    3113142
32    3113124
33    3113116
34    3113143
35    3113103
36    3113115
37    3113101
38    3113102
39    3113133
40    3113136
41    3113121
42    3113123
Name: post_id, dtype: object
0     0000000
1     3111301
2     3111302
3     3111311
4     3111312
5     3111306
6     3111307
7     3111303
8     3111313
9     3111305
10    3111304
Name: post_id, dtype: object
0     0000000
1     3114321
2     3114344
3     3114303
4     3114312
5     3114331
6     3114403
7     3114402
8     3114316
9     3114317
10    3114305
11    3114405
12    3114323
13    3114342
14    3114301
15    3114313
16    3114315
17    3114325
18    3114341
19    3114404
20    3114401
21    3114304
22    3114406
23    3114322
24    3114343
25    3114314
26    3114335
27    3114324
28    3114333
29    3114332
30    3114407
31    3114302
32    3114306
33    3114334
34    3114311
Name: post_id, dtype: object
0     0000000
1     3191102
2     3191101
3     3191119
4     3191104
5     3191106
6     3191109
7     3191114
8     3191103
9     3191113
10    3191117
11    3191105
12    3191107
13    3191111
14    3191116
15    3191118
16    3191115
17    3191112
18    3191108
Name: post_id, dtype: object
0     0000000
1     3193534
2     3193541
3     3193538
4     3193551
5     3193515
6     3193531
7     3193366
8     3193513
9     3193535
10    3193703
11    3193704
12    3193556
13    3193521
14    3193363
15    3193701
16    3193522
17    3193512
18    3193361
19    3193362
20    3193543
21    3193533
22    3193524
23    3193555
24    3193514
25    3193526
26    3193511
27    3193554
28    3193536
29    3193365
30    3193705
31    3193542
32    3193537
33    3193523
34    3193544
35    3193702
36    3193525
37    3193553
38    3193364
39    3193552
40    3193532
Name: post_id, dtype: object
0     0000000
1     3000424
2     3000409
3     3000422
4     3000411
5     3000416
6     3000413
7     3000402
8     3000425
9     3000433
10    3000421
11    3000420
12    3000419
13    3000414
14    3000432
15    3000404
16    3000426
17    3000435
18    3000408
19    3000436
20    3000418
21    3000427
22    3000428
23    3000434
24    3000401
25    3000405
26    3000403
27    3000415
28    3000410
29    3000437
30    3000412
31    3000431
32    3000423
33    3000407
34    3000417
35    3000406
Name: post_id, dtype: object
0     0000000
1     3000301
2     3000306
3     3000331
4     3001151
5     3001152
6     3000324
7     3000313
8     3000341
9     3000323
10    3000303
11    3000335
12    3000314
13    3000304
14    3000315
15    3001154
16    3000322
17    3001157
18    3000311
19    3001153
20    3000325
21    3000334
22    3001158
23    3000305
24    3000332
25    3000337
26    3000312
27    3000336
28    3000302
29    3000321
30    3001156
31    3000326
32    3001159
33    3001155
34    3001161
35    3000333
Name: post_id, dtype: object
0     0000000
1     3001404
2     3001403
3     3001324
4     3001332
5     3001322
6     3001334
7     3001327
8     3001406
9     3001314
10    3001401
11    3001315
12    3001311
13    3001333
14    3001336
15    0000000
16    3001323
17    3001312
18    3001321
19    3001402
20    3001316
21    3001325
22    3001331
23    3001335
24    3001326
25    3001337
Name: post_id, dtype: object
0     0000000
1     3003555
2     3003556
3     3003519
4     3003535
5     3003562
6     3003531
7     3003514
8     3003534
9     3003571
10    3003552
11    3003515
12    3003554
13    3003526
14    3003503
15    3003533
16    3003537
17    3003521
18    3003513
19    3003551
20    3003512
21    3003505
22    3003501
23    3003502
24    3003541
25    3003543
26    3003572
27    3003511
28    3003516
29    3003517
30    3003536
31    3003506
32    3003539
33    3003504
34    3003525
35    3003518
36    3003523
37    3003538
38    3003527
39    3003545
40    3003524
41    3003561
42    3003553
43    3003542
44    3003522
45    3003532
46    3003565
47    3003564
48    3003563
49    3003544
Name: post_id, dtype: object
0     0000000
1     3060303
2     3060311
3     3060314
4     3060304
5     3060308
6     3060315
7     3060307
8     3060302
9     3060301
10    3060316
11    3060312
12    3060306
13    3060305
14    3060317
15    3060313
Name: post_id, dtype: object
0     0000000
1     3060422
2     3060407
3     3060414
4     3060427
5     3060426
6     3060434
7     3060424
8     3060412
9     3060402
10    3060401
11    3060411
12    3060432
13    3060403
14    3060421
15    3060405
16    3060404
17    3060431
18    3060425
19    3060416
20    3060423
21    3060413
22    3060435
23    3060406
24    3060417
25    3060415
Name: post_id, dtype: object
0     0000000
1     3001603
2     3001634
3     3001602
4     3001612
5     3001635
6     3001626
7     3001633
8     3001632
9     3001611
10    3001605
11    3001601
12    3001616
13    3001614
14    3001624
15    3001615
16    3001623
17    3001625
18    3001636
19    3001631
20    3001613
21    3001622
22    3001621
23    3001606
24    3001604
Name: post_id, dtype: object
0      0000000
1      3291113
2      3200845
3      3200818
4      3210404
        ...
277    3200838
278    3291116
279    3200841
280    3200072
281    3210139
Name: post_id, Length: 282, dtype: object
0      0000000
1      3260052
2      3260062
3      3260328
4      3260823
        ...
111    3260801
112    3260804
113    3260035
114    3260843
115    3260024
Name: post_id, Length: 116, dtype: object

KeyboardInterrupt:

In [ ]:
import glob
import re
import os

In [ ]:
for file in municipalities_csv_files:
    df_municipalitie_data = pd.read_csv(file)
    municipalities = df_municipalitie_data["municipalitie"].unique()
    for municipalitie_name in municipalities:
        df_municipalitie = df[df["municipalitie"] == municipalitie_name]
        
        s_another_name = df_municipalitie["another_name"].unique()
        s_another_name_kana = df_municipalitie["another_name_kana"].unique()
        
        post_nums =  []
        for s in s_another_name:
                 post_nums.append(df[((df["another_name"] == s) & (df["municipalitie"] == name))]["post_id"].values)
                
        post_numpy_list = np.array(post_nums)

        df_another_name = pd.DataFrame(s_another_name)
        df_another_name_kana = pd.DataFrame(s_another_name_kana)
        
        df_post_num = pd.DataFrame(post_numpy_list)
        
        df_another_names = pd.concat([df_another_name, df_another_name_kana,df_post_num], axis=1, join='outer')

        df_another_names.to_csv("csv/another_names/" + conv.do(municipalitie_name) + ".csv", index=None, header=["another_name","another_name_kana", "post_id"])